### ISSUE TITLE
Feature Request: disable drawer method

### ISSUE THREAD

**Issue by timdoes** [root-two/react-native-drawer#1]
Hi,

Do you plan on adding a method for disabling the drawer?

Thanks,
-Tim

**Comment by rt2zz** [comment]
You can call `closeDrawer` on the component, e.g. `this.refs.myDrawerRef.closeDrawer()`
also `openDrawer` works.

Does that solve your use case? 

I like the idea of being able to control the open/close from props, but currently open/close is in the component state, and I am reluctant to having control shared between the parent and the component itself.

**Comment by timdoes** [comment]
I was thinking more along the lines of disabling the drawer for a login screen or other views that do not warrant a side menu. I know there are workarounds but I was curious if you planned on creating a disable method.

Thanks,
-Tim

**Comment by rt2zz** [comment]
ah, I see. I agree it would make sense to add a `disabled` or `disableDrawer` prop. 

Will do soon

**Comment by rt2zz** [comment]
just release v0.0.5 which includes a disabled prop, as well as some other enhancements

**Comment by timdoes** [comment]
Thank you!
