### ISSUE TITLE
Android Drawer Styles Not Working

### ISSUE THREAD

**Issue by stolinski** [root-two/react-native-drawer#100]
Using this example direct from the readme

```
//Material Design Style Drawer
<Drawer
  type="overlay"
  content={<ControlPanel />}
  tapToClose={true}
  openDrawerOffset={0.2} // 20% gap on the right side of drawer
  panCloseMask={0.2}
  closedDrawerOffset={-3}
  styles={{
    drawer: {shadowColor: '#000000', shadowOpacity: 0.8, shadowRadius: 3},
    main: {paddingLeft: 3}
  }}
  tweenHandler={(ratio) => ({
    main: { opacity:(2-ratio)/2 }
  })}
  >
    <Main />
</Drawer>
```

The drawer looks correct on iOS, but on Android v6, there is no shadow, the drawer is transparent and has not background color. The same code looks fine in iOS.

**Comment by Taakn** [comment]
Shadows are not implemented in React Native on Android
https://facebook.github.io/react-native/docs/known-issues.html

I just created a new issue requesting the elevation prop to be added

**Comment by Taakn** [comment]
This the following issue on how to add shadows on Android:
https://github.com/root-two/react-native-drawer/issues/101

**Comment by rt2zz** [comment]
closing since elevation can be specified in styles per #101
