### ISSUE TITLE
Adding elevation prop

### ISSUE THREAD

**Issue by Taakn** [root-two/react-native-drawer#101]
Hello,

Since shadows are not available in Android, would it be possible to add the elevation prop?

Thanks so much

**Comment by Taakn** [comment]
Nevermind, that's already possible:

```
styles={{
  drawer: {shadowColor: '#000000', shadowOpacity: 0.8, shadowRadius: 3, elevation: 16},
  main: {paddingLeft: 3}
}}
```

And from [Material Design Specs](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs):

> Elevation
> 
> The nav drawer spans the full height of the screen, including behind the status bar, at a resting elevation of 16dp. Everything behind the drawer is still visible but darkened by a scrim.

**Comment by rt2zz** [comment]
Good to know elevation can be set on styles!
