### ISSUE TITLE
Incompatible with the ToolbarAndroid using the onIconClicked event

### ISSUE THREAD

**Issue by rwngallego** [root-two/react-native-drawer#106]
Hi there!

I've been trying to add the **ToolbarAndroid** component and handling the **onIconClicked** event. However I've seen this line of code does not allow the Drawer to be opened:

https://github.com/root-two/react-native-drawer/blob/master/index.js#L304

The open event is fired but the Drawer never gets opened. If I try the same with a **TouchableHighlight** component and associating it to the **onPress** event it works prety well.

So, I've logged the object before exiting the open method:

```
I/ReactNativeJS( 2445): { _rafLoop: [Function],
I/ReactNativeJS( 2445):   terminate: [Function],
I/ReactNativeJS( 2445):   _t0: 1456640135299,
I/ReactNativeJS( 2445):   _config: 
I/ReactNativeJS( 2445):    { start: 0,
I/ReactNativeJS( 2445):      end: 0,
I/ReactNativeJS( 2445):      easingType: 'linear',
I/ReactNativeJS( 2445):      duration: 350,
I/ReactNativeJS( 2445):      onFrame: [Function],
I/ReactNativeJS( 2445):      onEnd: [Function] } }
```

By removing that problematic line of code the drawer seems to work as expected. I've checked and the whole component works good as well. My question for you guys is: it is possible to get rid of that condition or do we need to add an additional conditional check in order to not exit the open method call and get the Drawer to be compatible with the ToolbarAndroid component? Thank you!

This is an idea of my code:

``` javascript
  iconClicked = () => {
    this.refs['DRAWER'].open();
  }
  ...
        <Drawer 
            ref={'DRAWER'}
            ...
                <ToolbarAndroid
                    navIcon={require('./logo.png')}
                    title="My app name"
                    onIconClicked={this.iconClicked}
                    style={{height:56, backgroundColor: '#e9eaed'}}/>
```

**Comment by farwayer** [comment]
The problem is in `handlePanResponderEnd()` and/or `close()` functions:
1. User click to menu icon
2. `handlePanResponderEnd()` try to close drawer for some reason although it's already closed
3. tween animation run and set `this._activeTween != null`
4. ToolbarAndroid call drawer `open()`
5. `open()` check this._activeTween and exit without any actions (b6d57cf)
6. `close()` animation ended

**Comment by rt2zz** [comment]
sounds like the best option is to check the delta between https://github.com/root-two/react-native-drawer/blob/master/index.js#L330-L331 and only trigger the tween if the delta > 0.

**Comment by rwngallego** [comment]
@rt2zz I've tested what you proposed but the drawer has an animation lag when opening from the menu icon. I've ended with the app blocked too. Is there a better idea to handle that?

This is what I did:

```
  ...
  open = () => {
    this.props.onOpenStart && this.props.onOpenStart()
    var delta = this.getOpenLeft() - this._left;
    if (delta <= 0) return;
    this._activeTween = tween({
      start: this._left,
      end: this.getOpenLeft(),
      ...
```

**Comment by rt2zz** [comment]
Can you clarify what you mean by "I've ended with the app blocked too"?

I just release v2.0.0-alpha (`npm i react-native-drawer@next`) with the check for delta. I also changed a few other things about the way gestures are processed. While I have not tested your exact set up, I have a similar setup on my project and it is working much more consistent now. Let me know how that goes for you.

**Comment by rwngallego** [comment]
Well, I meant the drawer was keeping opened and didn't respond to any gestures after certain use, so I had to close the app. I'll give it a try to the new version and I'll tell you how was it going.

**Comment by rwngallego** [comment]
Could not get the latest version:

```
npm i react-native-drawer@next
react-native-drawer@2.0.0-alpha6  invalid
```

**Comment by rwngallego** [comment]
I was able to updated it by changing the version number to `react-native-drawer@next` in my package.json and I've tested it again: It works pretty well now when I click the androidtoolbar. Thank you guys! The new version rocks. It's really smooth!

**Comment by rt2zz** [comment]
@rwngallego awesome! I think there are still some bugs that need ironing out, but in general the new version should be smoother.

**Comment by rt2zz** [comment]
I believe this is resolved now, if not please reopen
