### ISSUE TITLE
Console.error: undefined is not an object(evaluating 'this.drawer.open')

### ISSUE THREAD

**Issue by silentsiri** [root-two/react-native-drawer#107]
I update the latest version v1.16.7.

and change the way to open the drawer from

``` js
this.refs.draw.open()
```

to 

``` js
this.drawer.open()
```

and it makes error.

and some code in my component:

``` js
<Drawer ref="drawer"
  type="static"
  openDrawerOffset={DRAWER_OFFSET}
  panOpenMash={.8}
  content={<DrawerScene closeDrawer={this.closeDrawer} />}>

  <MainView
    drawerStatus={this.state.isDrawerOpened}
    closeDrawer={this.closeDrawer}
    openDrawer={this.openDrawer}/>
</Drawer>
```

**Comment by rt2zz** [comment]
the correct syntax is `this.refs.drawer.open()`. Since you have a string ref, the ref gets added to the ref object. Can you try again and report back if that is working for you?

**Comment by silentsiri** [comment]
@rt2zz But in the `README.md` is `this.drawer.open()`. Is it something wrong?

And now I could not run `npm start` in the example.It has error in `index.js` file

**Comment by rt2zz** [comment]
good call, I just updated the readme. 

I am working on a new stripped down example. There is probably a conflict with the latest version of react-native.

**Comment by silentsiri** [comment]
well, when you finish work on the example, @ me please. 

To keep my project on, I go back to the version v1.8.0...

and this error made in the latest version example:

![image](https://cloud.githubusercontent.com/assets/9881593/13483878/9346d180-e133-11e5-94d2-f70a753a89c0.png)

**Comment by rt2zz** [comment]
@futurefeeling sorry for the delay. There is a new example at `./examples/RNDrawerExample` that is a lot easier to tinker with (albeit ugly!). There have also been a lot of bug fixes in the last 2 weeks, I recommend you try `npm install --save react-native-drawer@next`

**Comment by silentsiri** [comment]
@rt2zz thanks, I'm running your example - [RNDrawerExample](https://github.com/root-two/react-native-drawer/tree/master/examples/RNDrawerExample) , but made some trouble in `package.json` file:

``` json
"dependencies": {
    "react-native": "^0.21.0",
    "react-native-drawer": "github:rt2zz/react-native-drawer"
}
```

maybe the reason of problem made is that I use a `npm mirror` named `taobao`, so I modified the dependencies and fixed that.

Thanks a lot

**Comment by rt2zz** [comment]
Glad you got that working. When things start to stabilize I will change that dep to reference npm but for now it sounds like everything is working :+1:

**Comment by prakasa1904** [comment]
same issues, its not good if we need changes version, right
