### ISSUE TITLE
Android with React 0.21

### ISSUE THREAD

**Issue by Ksantor** [root-two/react-native-drawer#108]
I have to admit, haven't investigated this much, but it looks like react-native-drawer doesn't work with React-Native 0.21.

The app just crashes as soon as `react-native-drawer` is imported, required or included in packager.json

**Comment by rt2zz** [comment]
That is unlikely as this is purely a JS module, it is unlikely there are android specific exceptions.

I will give this a try tonight

**Comment by Ksantor** [comment]
I think I found, what exactly is causing the crash.

```
<Drawer
  tapToClose={ true }
>
```

I'm running exactly the same code for iOS (9.1.1) and Android (5.0.1 and 5.1.1).
On React 0.20 everything worked smoothly, since 0.21, `tapToClose` prop for `Drawer` causing the android app to crash. Without `tapToClose` everything works fine.

**Comment by Ksantor** [comment]
I think I found, what exactly is causing the crash. (Not really related to React 0.21)

I had `tapToClose={ true }` prop defined twice for `Drawer`

```
<Drawer
  tapToClose={ true }
  ...
  tapToClose={ true }
>
```

I'm running exactly the same code for iOS (9.1.1) and Android (5.0.1 and 5.1.1).
Defining `tapToClose` twice causing the android app to crash.

Since it is my mistake, I think the issue can be closed.

Sorry.

**Comment by rt2zz** [comment]
:+1:
