### ISSUE TITLE
Setting Drawer State to Open or Closed Using Properties

### ISSUE THREAD

**Issue by bbar** [root-two/react-native-drawer#109]
First off, awesome package. Thank you.

I'm using the drawer component with redux and am wondering if there's a way to set the state to either open or closed using properties. I know we can use the drawer.open() and drawer.close() methods, but I'm wondering if there's a way to set it to open or closed using a property, similar to how we can set the "disabled" property to true or false.

**Comment by bbar** [comment]
I submitted pull request #110 for a possible implementation of this.

**Comment by rt2zz** [comment]
Accepted, and release in react-native-drawer@next (v2.0.0-alpha) :+1:

**Comment by jayesbe** [comment]
@bbar How did you connect the Drawer to redux ?  I am trying and as soon as I try to toggle the Drawer it throws an exception

```
undefined is not an object (evaluating '_this2.drawer.toggle
```

**Comment by rt2zz** [comment]
that error would indicate to me that your refs are not set up correctly. You might want to try callback refs: `ref={(ref) => this.drawer = ref}}`

Other than that you can also try using the new declarative `open` prop:
`<Drawer open={ true | false } ... />`

**Comment by jayesbe** [comment]
Actually just found a solution on https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

needed to pass the 'withRef' option into redux. All good now.
