### ISSUE TITLE
Control drawer using props

### ISSUE THREAD

**Issue by Kureev** [root-two/react-native-drawer#112]
Is it possible to control a drawer using a plain props?

I'd like to keep state of the drawer outside of the component and pass it using props, for instance:

``` jsx
<Drawer isOpen={true}>...</Drawer>
```

Is there any way to do it?

I saw an `open` parameter, but after looking into the code, it seems that this state change wouldn't be animated, right?

**Comment by rt2zz** [comment]
Yes, this will be supported in 2.0 with the open prop. If animations are not triggering let me know and I will fix. V2 is still very much a wip.

**Comment by bbar** [comment]
I'm using the new 2.0 version (`npm install react-native-drawer@next)` and the animations are working with the open property. If you're keeping track of the drawer's state outside of the component itself (with redux, or whatever), you'll probably want to make use of the onOpen and onClose properties to keep your state up-to-date jic something other than your global app state triggers the open or close (setting `tapToClose={true}`, for example).

**Comment by Kureev** [comment]
@bbar I find `onOpen` and `onClose` callback useful only in the case if you have a complex animation sequence and you need to schedule a next animation action after drawer animation. Otherwise you can just send a change event immediately tap (to close) and [define a `componentWillReceiveProps` to avoid re-triggering the animation](https://github.com/react-native-fellowship/react-native-side-menu/blob/master/index.js#L65-L69)

**Comment by bbar** [comment]
@Kureev The problem I'm concerned about occurs when state is managed in two different places. For example, a redux state tree and the actual drawer component. I'm using redux, so if I want to open the drawer, I just dispatch an 'OPEN' action, the state tree is updated, the drawer component receives a new open prop of 'true' and the drawer opens. The same thing happens if I dispatch a 'CLOSE' action from my app. However, what happens if the request to open or close the drawer comes from the drawer component itself? In that case, the redux state tree isn't updated. So I'm using the `onOpen` and `onClose` props to update the state tree (by dispatching an action).

I don't like it either, but am definitely open to suggestions.

**Comment by Kureev** [comment]
Well, I'm using a hack now:

``` jsx
class SomeContainer extends Component {
  componentWillReceiveProps(nextProps) {
    if (this.props.isMenuOpened !== nextProps.isMenuOpened) {
      if (nextProps.isMenuOpened) {
        this.context.drawer.open();
      } else {
        this.context.drawer.close();
      }
    }
  }

  render() {
    return (
      <SomeComponent
        {...this.props}
        openDrawer={this.context.drawer.open}
        closeDrawer={this.context.drawer.close}/>
    );
  }

  static contextTypes = {
    drawer: React.PropTypes.object,
  };
}

function mapStateToProps(state) {
  return {isMenuOpened: state.menu.isOpened};
}

function mapDispatchToProps(dispatch) {
  return {actions: bindActionCreators(actions, dispatch)};
}

export default connect(mapStateToProps, mapDispatchToProps)(SomeContainer);
```

and in the code its usage looks like this:

``` jsx
<Drawer {...someProps}>
  <ScrollableTabView renderTabBar={() => <SomeContainer/>}>
  ...
  </ScrollableTabView>
</Drawer>
```

**Comment by Kureev** [comment]
Ideally, I'd like to see that Drawer works like new NavigatorExperimental (by implementing a small self-written redux architecture). If you go with this approach, it'll allow you to build an architecture, that can be integrated with redux without problems. But this issue is solved, so I don't see a point to keep it opened. If you want to discuss it - feel free to ping me on a facebook or twitter :wink:
