### ISSUE TITLE
Make a `mainOverlay` customizable thru the `tweenHandler`

### ISSUE THREAD

**Issue by Kureev** [root-two/react-native-drawer#113]
I have a case where I need to change a color of the overlay, but currently I can change a background color of `drawer` or `main` layers only. 

Possible solution: to add `overlay` to the export object `tweenHandler` function.

**Comment by rt2zz** [comment]
this required a few changes in the way mainOverlay worked. I now have mainOverlay using `pointerEvents` to captureGestures. This freed up the possibility to style mainOverlay which is now possible:

```
<Drawer 
  styles={{mainOverlay: {/*styles*/}}}
  tweenHandler={(ratio) => ({
    mainOverlay: { opacity: ratio }
  })
  >
  // ...
```

This is all very fresh in the 2.0 branch (`npm i react-native-drawer@next`). Let me know if that works!

**Comment by Kureev** [comment]
Thanks! I'll close it up for now and test it when I'll have a chance. If your suggestion wouldn't work, I'll reopen it again.
