### ISSUE TITLE
Trying to use a burger menu which toggles my drawer

### ISSUE THREAD

**Issue by BigPun86** [root-two/react-native-drawer#115]
Hey there! 

Like mentioned in the title i would like to use a burger menu icon/button to open and/or close my drawer. I am using a react-native-simple-router which makes my navbars. This is where i render my router and where i give my route "dashboard" a leftButton:

```
-------------------
<Route name="dashboard" schema='modal'>
<SideDrawer ref="drawer">
    <Router hideNavBar={false}>
    <Route name='home' component={ Routes.Dashboard } title={translate('dashboard')}  renderTitle={renderTitle} renderLeftButton={renderBurgerMenu}/>
-------------------
```

renderLeftButton is has a simple function which returns a ButtonView/Image:

```
function renderBurgerMenu() {
  return (
    <View>
        <TouchableHighlight
            onPress={() => {this.drawer.open()}} // Tried this too this.refs.drawer.open()
            underlayColor='transparent'
        >
            <Image style={{resizeMode: 'contain'}} source={Theme.Images.ICONS_BURGER_MENU}/>
        </TouchableHighlight>
    </View>
  )
}
```

<img width="392" alt="screen shot 2016-03-06 at 23 48 36" src="https://cloud.githubusercontent.com/assets/7880624/13557699/fba819e0-e3f5-11e5-9c07-3a2c1413c268.png">

Any ideas how to solve this? I tried using context too, but had similar issues...

**Comment by rt2zz** [comment]
It looks like the way you have renderBurgerMenu defined is outside of your parent component, so this will not be bound and refs/context will not be available. Try definining thr method as a class property on your component and then calling this.renderBurgerMenu instead.

**Comment by BigPun86** [comment]
@rt2zz Unfortunately it didn´t work...:

```
renderBurgerMenu() {
    console.log('REFS',this.refs, this);
    return (
        <View>
            <TouchableHighlight
                onPress={()=>this.refs.drawer.open()}
                underlayColor='transparent'
            >
                <Image style={{resizeMode: 'contain'}} source={Theme.Images.ICONS_BURGER_MENU}/>
            </TouchableHighlight>
        </View>
    )
}

render() {

    return (
        <View style={{flex: 1}}>
            <Router hideNavBar={true}>
                <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}
                        titleStyle={{color: 'white'}}
                        backButtonStyle={{tintColor: 'white'}}
                        navigationBarStyle={{backgroundColor: Theme.Colors.MAIN, borderBottomWidth: 0}}
                        barButtonText={{color: 'white'}}/>

                <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}
                        titleStyle={{color: 'white'}}
                        backButtonStyle={{tintColor: 'white'}}
                        navigationBarStyle={{backgroundColor: Theme.Colors.MAIN, borderBottomWidth: 0}}
                        barButtonText={{color: 'white'}}
                />

    <Route name="dashboard" schema='modal'>
                    <SideDrawer ref="drawer">
                        <Router hideNavBar={false}>
                            <Route name='home' component={ Routes.Dashboard } title={translate('dashboard')} type='reset'
                                   renderTitle={renderTitle}
                                   hideNavBar={true}
                                   renderLeftButton={this.renderBurgerMenu.bind(this)}/> // this.renderBurgerMenu
```

**Comment by rt2zz** [comment]
I see, this is a little tricky. I am not clear on the implementation of Router, but it may be creating an intermediate layer of refs (i.e. this.refs.router.refs.drawer). One possible things to try:
- change `<SideDrawer ref="drawer">` to `<SideDrawer ref={(drawer) => this.drawer = drawer}>`. String refs are being deprecated anyway, and if this works I will update the docs accordingly.

If that doesnt work, you might try searching through the object logged in `console.log('REFS',this.refs, this);` to see if you can find the drawer anywhere.

**Comment by BigPun86** [comment]
We´ll that makes sense. But still it won´t work this way. But i got it working before just like you thought with this.refs.drawer.refs.drawer.open(). Doesn´t look nice but does it´s job :) Thanks for the effort @rt2zz

**Comment by rt2zz** [comment]
Sounds good :+1: if you figure out anything more elegant let us know
