### ISSUE TITLE
how I can change the drawer's content

### ISSUE THREAD

**Issue by moxiaobei2** [root-two/react-native-drawer#116]
I want some changes in the open drawer,when the main's dom is onPressed,the drawer is opened,at the same time,I should change the content of the drawer,how???

**Comment by rt2zz** [comment]
have you tried simply changing the JSX you give to the `content` prop?

i.e.

``` js
<Drawer
  content={ this.state.something ? this.renderDrawerOne() : this.renderDrawerTwo() }
// ...
```

**Comment by moxiaobei2** [comment]
u get my mind,thank you so much~@rt2zz

**Comment by rt2zz** [comment]
:+1: :D
