### ISSUE TITLE
Touch to close triggers click

### ISSUE THREAD

**Issue by 9mm** [root-two/react-native-drawer#118]
Hey, I'm using react-native-drawer on my iOS project. It works really great, except when I go to close it with a swipe, it triggers a click on the swipe location if the movement is subtle enough. I have to very exaggerated drag and click to get it to close without clicking on the thing under my thumb.

Is there some way to disable clicking while it's open? Or some other way around this... thanks!

**Comment by hashwin** [comment]
I fixed this by adding captureGestures={true} to the props.

**Comment by 9mm** [comment]
I can't seem to get that to behave properly, for me it just freezes the app so nothing is clickable ;/

**Comment by paulwcy** [comment]
Same here... and drawer is closed as soon as my finger touches the screen. Is it possible to configure on-touch-up instead of on-touch?

**Comment by 9mm** [comment]
Fixed by using [latest version](https://github.com/root-two/react-native-drawer/commit/856bae257239e6b54969ecc94c6e55d71339358a) on master. Thanks!

@paulwcy in case you need it here is my config

```
  <DrawerIOS
    content={sidebarContent}
    disabled={!!this.props.modalValues.hasModals}
    ref="drawer"
    type="static"
    onOpenStart={() => {
      this._hideKeyboard();
      this._setStatusBarHidden(true);
    }}
    onOpen={() => this.setState({isDrawerOpened: true})}
    onCloseStart={() => this._setStatusBarHidden(false)}
    onClose={() => this.setState({isDrawerOpened: false})}
    openDrawerOffset={0.2}
    panOpenMask={0.2}
    captureGestures="open"
    negotiatePan={true}
    tapToClose={true}
    styles={styles.ios}
    tweenDuration={110}
    tweenEasing="easeInOutCirc">
    {content}
  </DrawerIOS>
```
