### ISSUE TITLE
Unexpected behaviour onOpen onClose in v2.0.0

### ISSUE THREAD

**Issue by DavoCg** [root-two/react-native-drawer#119]
Hi,

I've just switched from 1.16.x to v2.0.0 alpha and I have an unexpected behaviour with onOpen and onClose props.

this is my drawer component :

```
         <Drawer
                ref={"drawer"}
                type="static"
                content={<Menu items={items} {...this.props} navigate={this.navigate}/>}
                openDrawerOffset={0.35}
                styles={{main: {shadowColor: "#000000", shadowOpacity: 0.3, shadowRadius: 15}}}
                onOpen={() => this.setState({drawerOpen: true})}
                onClose={() => this.setState({drawerOpen: false})}
                captureGestures={false}
                tweenDuration={100}
                negotiatePan={true}
                panThreshold={0.08}
                panOpenMask={0.35}
                disabled={this.state.drawerDisabled}
                tweenHandler={Drawer.tweenPresets.parallax}>
```

I need to set state with drawerOpen [true or false] when drawer open or close to open or close it programatically with this method : 

```
toggle(){
        const fn = this.state.drawerOpen ? 'close' : 'open';
        this.refs.drawer[fn]();
    }
```

On previous version everything works well but now : 
 When I open the drawer (programatically or with swipe gesture) the component re render and the drawer close automatically.

Maybe i missed something but i've tried all props and i can't make it works.

Thanks for this amazing module v2 is a really smooth 

DavoCg

**Comment by DavoCg** [comment]
I figured out that new feature added by #110 fix my problem (even if it make animation a little bit less smooth)

**Comment by rt2zz** [comment]
@DavoCg there was a bug in the implementation around #110 that is now resolved :+1:
