### ISSUE TITLE
Right side drawer

### ISSUE THREAD

**Issue by liubko** [root-two/react-native-drawer#12]
this will be very useful :pray:

**Comment by rt2zz** [comment]
Agreed. I want to generalize the functionality to work from any direction (up, down as well).

In a new branch https://github.com/rt2zz/rn-drawer/tree/rightside I implemented a new prop `side` (either left or right).

I am not super happy with the code organization so I am not sure if I will merge to master any time soon. But if you want to play around with it you can clone that branch.

**Comment by rt2zz** [comment]
After thinking about this more, I would like to take a more generalized approach. Ideally we would support an arbitrary number of drawers, perhaps stored in an array. We could even go one level deeper and allow for vertical drawers (array of arrays). Not sure what the API would look like

**Comment by rt2zz** [comment]
Ok, well as I am not sure when I will get around to the multi-panel rewrite, I merged this in.

Set `side="right"` to get a right hand drawer (in v1.2.1)
