### ISSUE TITLE
Can't close drawer on latest commit

### ISSUE THREAD

**Issue by holyxiaoxin** [root-two/react-native-drawer#122]
Tested `https://github.com/root-two/react-native-drawer/blob/master/examples/RNDrawerExample/package.json` and find that after having the drawer fully opened, I am unable to close it.

Version v1.16 is working well. I believe that v2.0 is not stable and therefore we should not switch yet.

**Comment by rt2zz** [comment]
1. Thanks for finding that, there was a bug when the pan went to or past the max open. It is fixed now.
2. Yes you are right 2.0 is a wip, if you value stability 1.16 is a better choice.
3. If you do decide to stick with 2.0 please let me know if you run into any other inconsistencies and I will fix.
