### ISSUE TITLE
Problems with triggering the disabled prop for the drawer

### ISSUE THREAD

**Issue by BigPun86** [root-two/react-native-drawer#126]
Hey there! I am not sure how to use this prop correctly...My App is built up with a launch screen followed by a Registration/Login Screen. Now when i am on these Screens i don´t want the drawer to be displayed. I am using the react-native-simple-router for navigation. So the Drawer wraps the Router like this:

```
        <View style={{flex: 1}}>
            <SideDrawer ref="drawer" router={this.refs.router}>
                <Router
                    ref="router"
                    firstRoute={{
                        name: '',
                        component: Routes.Launch,
                        hideNavigationBar: true
                    }}
                    titleStyle={Theme.mix('textSemiBold|medium|regular')}
                    headerStyle={{backgroundColor: Theme.Colors.MAIN, elevation: 5}}
                    noStatusBar={true}
                    statusBarProps={{
                        statusBarColor: 'black',
                        backgroundColor: 'transparent',
                        hidden: Platform.OS !== 'ios',
                        translucent: true
                    }}
                    statusBarColor={'black'}
                    backButtonComponent={BackButton}
                    handleBackAndroid={true}
                    customAction={this.handleCallbacks.bind(this)}
                />
                <LoadingOverlay
                    isVisible={Spots.isFetching || Users.isFetching || Channels.isFetching || User.isFetching || Reviews.isFetching || Media.isFetching}
                    text={translate('loading')}
                />
            </SideDrawer>
            {this.renderAdBanner()}
        </View>
```

Drawer:

```
export default class SideDrawer extends Component {

constructor(props) {
    super(props);
}

render() {
    var facebookUser = store.getState().facebook;
    return (
        <Drawer
            ref="drawer"
            type="overlay"
            content={<Menu  {...this.props} facebookUser={facebookUser}/>}
            tapToClose={true}
            openDrawerOffset={0.2}
            panCloseMask={0.2}
            closedDrawerOffset={0}
            tweenHandler={(ratio) => ({ main: { opacity: (2 - ratio) / 2 } })}
            disabled={this.props.router ? this.props.router.refs.navigator.getCurrentRoutes()!=='dashboard':true}
        >
            {React.Children.map(this.props.children, c => React.cloneElement(c, {
                route: this.props.route
            }))}
        </Drawer>
    )
}

}
```

Now this actually works well until i try to close the drawer. The drawer can only be opened when i am on the dashboard component, which is what i want. But there seems to be a bug or i am using it not correctly. I can´t close the drawer until i go to a other screen...

Any ideas how to trigger disabled prop for my case?

**Comment by rt2zz** [comment]
Are you using v1.16? There is a bug, the workaround is to set `acceptPan={true|false}` in addition to disabled.

The better solution is to upgrade to 2.0 `npm i --save react-native-drawer@next` which while still under development has better logic for pans and disabling.

**Comment by BigPun86** [comment]
Yeah i was using 1.16.7. But unfortunately both won´t work, using acceptPan as well as upgrading to 2.0. If i set disabled "hardcoded" to false it works like it should, but that is default anyway. Do you have an example how u triggered it with any code snippet? Maybe it will help me.

**Comment by rt2zz** [comment]
I do not fully follow the issue here. 

Can you clarify the line
`disabled={this.props.router ? this.props.router.refs.navigator.getCurrentRoutes()!=='dashboard':true}`

This code appears to disabled the drawer on all pages except the dashboard. Is that the desired effect?

**Comment by BigPun86** [comment]
Yes thats what i wanted to have. But unfortunately every time i open the drawer i can´t close it anymore..So i used a other way. I am triggering it now by checking the userToken. So this means, when i am LoggedIn to the App, which should be after the Login Screen and Launch Screen etc. i am able to open/use the drawer

```
    var userToken = store.getState().User.token;
    return (
        <Drawer
            ref="drawer"
            type="overlay"
            content={<Menu  {...this.props} />}
            tapToClose={true}
            openDrawerOffset={0.2}
            panCloseMask={0.2}
            closedDrawerOffset={0}
            tweenHandler={(ratio) => ({ main: { opacity: (2 - ratio) / 2 } })}
            disabled={ userToken === '' || userToken === null || userToken === undefined }
        >
            {React.Children.map(this.props.children, c => React.cloneElement(c, {
                route: this.props.route
            }))}
        </Drawer>
    )
```

**Comment by rt2zz** [comment]
Sounds good, if you want to revisit the old way let me know. closing for now 👍
