### ISSUE TITLE
Scene can not display scroll

### ISSUE THREAD

**Issue by silentsiri** [root-two/react-native-drawer#128]
Everything is ok except the scene cannot scroll, like following pic:

![pic](https://cloud.githubusercontent.com/assets/9881593/14132307/017bdf12-f677-11e5-9c49-5de4039a5e3c.gif)

detail code in https://github.com/futurefeeling/FARSER

**Comment by rt2zz** [comment]
Your code is a bit dense, but I suspect it might be related to not having a height set on your scroll view. Try setting `style={{flex: 1}}` on your container components.

**Comment by silentsiri** [comment]
sorry, I had forgot to show the main file link. :cry: 

two files is the focus:

https://github.com/futurefeeling/FARSER/blob/master/components_scene/DrawerScene.js

and

https://github.com/futurefeeling/FARSER/blob/master/components_scene/GoddessScene.js

and if i change View Component to ScrollView Component in `GoddessScene.js` , it work. But I'm not sure whether this is the cause of the error.

**Comment by rt2zz** [comment]
Not sure I follow. You want to scroll on GoddessScene correct? in that case you definitely need to switch that View to be a ScrollView and will also want to set `flex:1` on the container style.

**Comment by silentsiri** [comment]
Thank you for taking the time to help me. :bow:
