### ISSUE TITLE
Is this supported by react-native 0.22

### ISSUE THREAD

**Issue by joshbedo** [root-two/react-native-drawer#129]
Does anyone know if this works with React Native 0.22?

**Comment by rt2zz** [comment]
Yes, I have it implemented in a an app running .22, are you experiencing issue?

**Comment by joshbedo** [comment]
Yeah the build was failing but let me investigate a little further. I might've not cleaned up everything running after the install.

**Comment by joshbedo** [comment]
So it's working now, i probably forgot to close the packager or something like that :p
