### ISSUE TITLE
RCTRootView.h file not found for the example project

### ISSUE THREAD

**Issue by chinciusan** [root-two/react-native-drawer#13]
I wanted to test the example project, but Xcode gives the "RCTRootView.h file not found" error.

**Comment by rt2zz** [comment]
Ah, I should have been stricter with the semver. I just pushed a commit that resolves the issue (no version bump though, so make sure you get the latest from git)

**Comment by chinciusan** [comment]
Yep. Works now. Great drawer, really useful!
