### ISSUE TITLE
Burger Menu Button

### ISSUE THREAD

**Issue by babbarankit** [root-two/react-native-drawer#130]
I want to have a Button on All Screens to open the Drawer. 
I am using "react-native-drawer": "^1.16.7", "react-native-router-flux": "^2.3.7"
I used the hints given on this project home page and also tried to search the issues, still I am unclear how can I create a button for this.

**Comment by rt2zz** [comment]
You can put a button anywhere you like and simply have onPress call `this._drawer.open()`

The only thing is you need to get a reference to the drawer. You can either use refs or context for this as described here https://github.com/root-two/react-native-drawer#opening--closing-the-drawer-programmatically

**Comment by caroaguilar** [comment]
If you're using NavigatorIOS there is a property called leftButtonIcon where you can add your icon
`leftButtonIcon: require('image!hamburgerIcon')` and then `onLeftButtonPress: () => this._drawer.open()`

If you're using Navigator is almost the same, so for example using the AndroidToolbar would be:

```
<ToolbarAndroid
    actions={[]}
    onIconClicked={() => this._drawer.open()}
    title="MyComponent" />
```

**Comment by rt2zz** [comment]
@caroaguilar thanks for more details. @babbarankit you should also consider upgrading to the latest drawer (v2).

Closing for now, feel free to reopen if still and issue.
