### ISSUE TITLE
ghost drawer

### ISSUE THREAD

**Issue by limulidae** [root-two/react-native-drawer#131]
the drawer is closed by default.

but, its last render() call produces a ghost drawer on screen.

how to work around it?

**Comment by rt2zz** [comment]
What do you mean by a ghost drawer? Can you post your Drawer configuration and also what version you have installed

**Comment by limulidae** [comment]
http://imgur.com/UEaYfjM
the drawer is closed, but still can see its content.

```
render() {
    return (
        <View style={styles.container}>
            <Drawer content={<IndexDrawer index={this} navigator={this.props.navigator}/>}
                    openDrawerOffset={0.6}
                    panCloseMask={0.6}
                    ref="drawer"
                    tapToClose={true}
                    tweenHandler={Drawer.tweenPresets.parallax}
                    type="static">
                <IndexBar index={this} navigator={this.props.navigator}/>
                <IndexContent index={this}/>
            </Drawer>
        </View>
    );
}
```

version react-native-drawer@2.0.0

ps.
manually open it http://imgur.com/GqjVB6b
manually close it http://imgur.com/HurOfrV

**Comment by rt2zz** [comment]
type="static" positions the drawer behind the main view, so the positioning is correct. It appears to me what you need is to set `backgroundColor: 'white'` on your main view. e.g.

```
<Drawer content={<IndexDrawer index={this} navigator={this.props.navigator}/>}
                    openDrawerOffset={0.6}
                    panCloseMask={0.6}
                    styles={{main: {backgroundColor: 'white'}}}
                    ...
```

`

**Comment by limulidae** [comment]
it works. million thanks.
