### ISSUE TITLE
Question: Drawer partially open, shadow over content area

### ISSUE THREAD

**Issue by mschipperheyn** [root-two/react-native-drawer#14]
I would like to have a shadow over the content area that is still visible when the drawer is open. 
Ideally, I would like this to fade in as the drawer open and fade out as it closes. 

Is this possible?

**Comment by rt2zz** [comment]
this is possible using a tween handler. I believe one of the readme examples has this. I will double check later

**Comment by rt2zz** [comment]
see the "material design style overlay" from the readme:

``` js
//Material Design Style Drawer
<Drawer
  type="overlay"
  openDrawerOffset={50} //50px gap on the right side of drawer
  panCloseMask={1} //can close with right to left swipe anywhere on screen
  styles={{
    drawer: {
      shadowColor: "#000000",
      shadowOpacity: 0.8,
      shadowRadius: 0,
    }
  }}
  tweenHandler={(ratio) => {
    return {
      drawer: { shadowRadius: Math.min(ratio*5*5, 5) },
      main: { opacity:(2-ratio)/2 },
    }
  }}
  content={<ControlPanel />}
  >
    <Main />
</Drawer>
```

You can adjust the opacity & shadow radius to your preference in the tweenHandler.

Does this solve your use case?

**Comment by mschipperheyn** [comment]
Thanks for the tips. I'm almost there. Just need to the main overlay to be black-based in stead of white-based. And the ability to click on the offset area to close the drawer. Great work BTW

**Comment by rt2zz** [comment]
when you say "main overlay to be black based" are you referring to the background color of the overlay drawer? You should be able to accomplish this with standard styling on your drawer component. Or you can specify additional styles in the styles prop:

``` js
styles={{
    drawer: {
      backgroundColor: 'black',
      shadowColor: "'000000',
      shadowOpacity: 0.8,
      shadowRadius: 0,
    }
  }}
```

As for clicking on the offset to close the drawer, this does not currently exist, but I like the idea. There is an `acceptDoubleTap` prop that may be sufficient in the meantime.

**Comment by mschipperheyn** [comment]
Hi, no, I mean the shadow over the content area that is still visible when you use an offset.

**Comment by rt2zz** [comment]
I see, this is not a trivial to achieve. You can set your app background color to black, but that will of course affect other things as well. 

Alternatively you could do something like follows (warning: untested):

``` js
<Drawer
  type="overlay"
  openDrawerOffset={50} //50px gap on the right side of drawer
  panCloseMask={1} //can close with right to left swipe anywhere on screen
  tweenHandler={(ratio) => {

     //Set native props on any component you have a ref to in your tween handler
     this.refs.main.setNativeProps({
       opacity:(2-ratio)/2,
    })

    return {
      drawer: { shadowRadius: Math.min(ratio*5*5, 5) },
    }
  }}
  content={<ControlPanel />}
  >
    <View style={{flex:1, background: 'black'}} />
      <MainView ref="main" />
    </View>
</Drawer>
```

Suggestions welcome for how to design an API to make this easier & more intuitive.

**Comment by mschipperheyn** [comment]
Yeah, no joy on this one. this.refs.main is not recognized.

**Comment by rt2zz** [comment]
Hm, per my test it is working. I think perhaps your ref="main" is a component that does not support `setNativeProps`

try wrapping it in a container View like follows:

``` js
render(){
  return(
    <Drawer
          ref="drawer"
          type="static"
          content={<ControlPanel />}
          tweenHandler={(ratio) => {
            this.refs.container.setNativeProps({
              opacity:1-ratio
            })
            return {}
          }}
          >
          <View ref='container'>
            <Navigator
              ref='navigator'
              style={{width: fullWidth, height:fullHeight}}
              navigationBarHidden={this.props.routeKey === 'auth' ? true : false}
              barTintColor='#CF1216'
              titleTextColor='#FFFFFF'
              initialRoute={route}
              renderScene={this.renderRoute}
              />
          </View>
        </Drawer>
})
```

**Comment by rt2zz** [comment]
let me know if that is not working

**Comment by djchie** [comment]
I know this is closed. But I recently attempted this as well with success so I thought I'd leave my code here for anyone else who wants to achieve this!

``` javascript
render: function() {
  var navigationView = (
    <NavigatorIOS 
      style={styles.container} 
      barTintColor='red'
      titleTextColor='white'
      tintColor='white'
      initialRoute={{
        title: 'Home',
        component: HomeView,
        leftButtonTitle: 'Menu',
        // leftButtonIcon: require('image!back_button'),
        onLeftButtonPress: () => this.showMenuSlider(),
      }}
    />
  );

  return (
    <Drawer
      type="overlay"
      openDrawerOffset={100}
      panCloseMask={1}
      ref="drawer"
      tweenHandler={(ratio) => {
        this.refs.shadowOverlay.setNativeProps({
           opacity: ((ratio * 1.5) / 2),
        });
        return {
          drawer: { shadowRadius: Math.min(ratio*5*5, 5) },
        }
      }}
      content={<DrawerView />}
    >
      {navigationView}
      <View ref="shadowOverlay" style={styles.overlay} />
    </Drawer>
  );
}

var styles = StyleSheet.create({
  container: {
    flex: 1,
    opacity: 1
  },
  overlay: {
    flex: 1,
    position: 'absolute',
    left: 0,
    top: 0,
    width: width,
    height: height,
    opacity: 0,
    backgroundColor: 'black',
  },
}
```

**Comment by rt2zz** [comment]
@djchie glad you got that working, this is very similar to how I have acheived the shadow in the past. 

However I just had a thought: what if you set the `closedDrawerOffset={-5}` and then set a permanent shadow on the drawer. This _might_ acheive essentially the same effect but be simpler and more performant.

**Comment by rt2zz** [comment]
I just tested it and setting `closedDrawerOffset={-5}` works, but should be offset with a `paddingLeft: 5` on the main view.

Updated readme accordingly

**Comment by jaspal747** [comment]
Thank you for this thread folks. I was looking to get a darker overlay.

I could achieve the same by using the "mainOverlay" and setting opacity on it.

    <Drawer
        ref={(ref) => this._drawer = ref}
        type="overlay"
        content={<Menu navigate={(route) => {
            this._navigator.push(navigationHelper(route));
            this._drawer.close();
        }}/>}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
        closedDrawerOffset={-3}
        backgroundColor="#333"
        styles={{
            drawer: {
                shadowColor: '#000000',
                shadowOpacity: 0.8,
                shadowRadius: 3,
                backgroundColor: '#fff',
                paddingTop: 40,
            },
            main: {
                paddingLeft: 3
            },
            mainOverlay: { 
               backgroundColor:'#000', 
               opacity: 0
            }
        }}
        tweenHandler={(ratio) => ({
            mainOverlay: { opacity:ratio/2},
    })}>
