### ISSUE TITLE
Can't change mainOverlay opacity in tweenHandler

### ISSUE THREAD

**Issue by Qizly** [root-two/react-native-drawer#145]
I want the main content to go dark when the drawer is open by setting the mainOverlay background to black and opacity to 0 and in tweenHandler tried to change the opacity but it doesn't seem to work:

``` javascript
<Drawer
        ref="navigation"
        type="displace"
        content={<SideMenu />}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
        styles={{mainOverlay: {backgroundColor: '#000000', opacity: 0}}}
        negotiatePan={true}
        tweenHandler={(ratio) => ({
          mainOverlay: { opacity: ( ratio / 2 )}
        })}
      >
```

Is this a bug or am I doing it wrong?

Thanks.

**Comment by Qizly** [comment]
This works.

``` javascript
tweenHandler={(ratio) => ({
    mainOverlayProps: { opacity: ( ratio / 2 )}
})}
```

**Comment by rt2zz** [comment]
Ah, a bug ideed. Short term workaround: enable captureGestures prop `captureGestures={true}`

**Comment by rt2zz** [comment]
I cut a pre-release with a fix for this and some other improvements as well available via `npm i react-native-drawer@next`

Let me know if that works for you

**Comment by Qizly** [comment]
Zack,

It’s perfect. Thank you.

Yong

**Comment by rt2zz** [comment]
:+1:

**Comment by garrettbland** [comment]
Don't know if anyone is still needing help, but I figured out how to make the area behind the drawer go darker with opacity. 

`tweenHandler={(ratio) => ({
                  mainOverlay:{ backgroundColor:"rgba(71, 71, 71,"+ (ratio)/1.5+")"},
                })}`

I just used rgba (which is supported by react native. Runs on both iOS and Android) and used the ratio to control the opacity. Hope that helps! @rt2zz @Qizly

**Comment by roseniltonreis** [comment]
@garrettbland Thank you very much :)
