### ISSUE TITLE
Fixed drawer width

### ISSUE THREAD

**Issue by skizzo** [root-two/react-native-drawer#146]
How can I re-layout the drawer's width after rotating my app from portrait to landscape mode? The problem is, the function for `openDrawerOffset` is only called once and not again after rotating, which means the when in landscape mode (or on a tablet), the menu takes **way** too much space.. Thanks!

**Comment by rt2zz** [comment]
@skizzo I the openDrawerOffset is recalculated after reorientation, I think the problem you are having is that openDrawerOffset is calculated from the right side of the screen, whereas you want fixed width (calculated from the left).

try `openDrawerOffset={(viewport) => viewport.width - 200}` which will make the drawer always be 200px wide.

**Comment by skizzo** [comment]
@rt2zz Thanks for the quick reply. I've tried that method, it result in a warning (Failed propType: Invalid prop of type function, expected number) and the drawer not being usable any more.. The propType issue makes sense, since the prop `openDrawerOffset` is defined as `PropTypes.number` in your index.js.

**Comment by rt2zz** [comment]
I think you need to update to version 2.1

https://github.com/root-two/react-native-drawer/blob/master/index.js

**Comment by skizzo** [comment]
That was exactly the problem. Sorry and thanks!

**Comment by rt2zz** [comment]
:+1:
