### ISSUE TITLE
Difference from react-native-side-menu?

### ISSUE THREAD

**Issue by tonyxiao** [root-two/react-native-drawer#156]
In the readme it was mentioned that this repo is inspired by 

https://github.com/react-native-fellowship/react-native-side-menu

Why create a new library? What's the difference between `react-native-drawer` and `react-native-side-menu`?

**Comment by rt2zz** [comment]
react-native-side-menu is simpler and I suspect more stable. If it works for your use-case I would definitely recommend it. You can get a pretty good idea of the difference by looking at the props supported by each.

**Comment by rt2zz** [comment]
👍
