### ISSUE TITLE
panCloseMask is not defined

### ISSUE THREAD

**Issue by sylvainbaronnet** [root-two/react-native-drawer#157]
With 2.0 and setting `panCloseMask={0.35}` to the drawer 

![screen shot 2016-05-09 at 12 02 28](https://cloud.githubusercontent.com/assets/1569516/15109882/ecbd0d9a-15dd-11e6-9985-02787609a228.png)

**Comment by bartvtende** [comment]
#153 has the fix you probably need, but it hasn't been merged into a new release so far.

**Comment by sylvainbaronnet** [comment]
ok thanks i'll wait next version

**Comment by bawn** [comment]
@bartvtende thanks

**Comment by mbernardeau** [comment]
@sylvainbaronnet 
Note that if you don't want to wait, you can temporarily use the following command to install directly from GitHub:

```
npm install https://github.com/root-two/react-native-drawer --save
```

**Comment by rt2zz** [comment]
EDIT: scratch that, just release 2.2.1
