### ISSUE TITLE
Closing the drawer on disable

### ISSUE THREAD

**Issue by mschipperheyn** [root-two/react-native-drawer#16]
When I logout a user, I disable the menu. 
However, it may still be open, so I need to close it. So I user

```
componentWillUpdate(){
  if(this.state.disabled)
    this.refs.drawer.close();
```

  },

However, the close method itself checks for the disabled state before it executes the close, preventing the menu from being closed. Not sure what the best way is to handle this. It's nice to have the control over the it, but it seems to make sense to autoclose when the drawer is disabled in an open state.

**Comment by rt2zz** [comment]
Interesting. We could allow programmatic changes even when disabled, although I am concerned this makes the `disabled` prop a bit ambiguous. Thoughts?

In the mean time I would rearrange your code to close the drawer first, then set to disabled (I actually have a similar implementation that works this way).

**Comment by rt2zz** [comment]
v1.2.x now contains an `acceptPan` prop. Setting that to false, (and not disabling the drawer) should result in the behaivor you seek.

**Comment by mschipperheyn** [comment]
Cool! I'll give it a go!
