### ISSUE TITLE
Remove gradient border from side menu?

### ISSUE THREAD

**Issue by aksonov** [root-two/react-native-drawer#172]
<img width="117" alt="screen shot 2016-06-08 at 14 55 34" src="https://cloud.githubusercontent.com/assets/1321329/15894976/155a7478-2d89-11e6-86cf-1868614ed753.png">

**Comment by rt2zz** [comment]
The gradient is not there by default. Check the styles you are passing into the drawer, you probably have a border shadow defined there

**Comment by aksonov** [comment]
You are right. For some reason shadow was a part of NavigationCard of new Navigation API from React Native :(
