### ISSUE TITLE
Multiple drawers (left and right)

### ISSUE THREAD

**Issue by Archon-** [root-two/react-native-drawer#18]
May be useful once this one is finished https://github.com/rt2zz/react-native-drawer/issues/12

**Comment by rt2zz** [comment]
agreed, I am experimenting with having an arbitrary amount of "panels" provided as an array. Not sure what the API will look like yet though. Presumably some use cases will warrant different props per panel.

**Comment by Archon-** [comment]
@rt2zz It sounds very promising. :+1: Is there any branch pushed here that I can look into?

**Comment by rt2zz** [comment]
Nothing sharable at the moment, it may be a while :(

**Comment by rt2zz** [comment]
EDIT: Woops wrong issue :/

**Comment by rt2zz** [comment]
if you need this soon, you might want to experiment with nesting Drawer components. There may be some nasty side effects, but theoretically it could work.

**Comment by rt2zz** [comment]
Working for me. Going to close this out.
