### ISSUE TITLE
Can't find variable: InteractionManager

### ISSUE THREAD

**Issue by mvaivre** [root-two/react-native-drawer#185]
I've just updated to `"react-native-drawer": "^2.2.6",` and `"react-native": "^0.29.0",` and I get the error in the title whenever I set the prop useInteractionManager to `true`.

**Comment by mvaivre** [comment]
Ok, it's a typo here: https://github.com/root-two/react-native-drawer/blob/master/index.js#L2

**Comment by rt2zz** [comment]
ty, just fixed in master will cut a release soon.

**Comment by kristojorg** [comment]
Any update on this? I am seeing significant performance problems where drawer is opening and closing with many seconds of dropped frames. I'm looking at using InteractionManager but am getting this error. 

On a side note, do you have recommendations on performance beyond this?

**Comment by nomoreboredom** [comment]
+1
