### ISSUE TITLE
transparent overlay only when the drawer is open

### ISSUE THREAD

**Issue by PierBover** [root-two/react-native-drawer#188]
I'd like to have a semi transparent overlay over the content like the one on these pictures.

![image](https://cloud.githubusercontent.com/assets/226483/16717045/175c8384-46d3-11e6-8b54-3de0402ad2a9.png)

I've tried using styles but `main` and `mainOverlay` seem to be always there, even if the drawer is closed.

So how can I achieve this result?

Thanks!

**Comment by dsibiski** [comment]
@PierBover Look at the answer here: https://github.com/root-two/react-native-drawer/issues/162

**Comment by PierBover** [comment]
Awesome @dsibiski
