### ISSUE TITLE
Unable to resolve module Dimensions from /project_path/node_modules/react-native-drawer/index.js

### ISSUE THREAD

**Issue by bleonard** [root-two/react-native-drawer#19]
I am getting this twice in the output when running
`react-native bundle --minify`

Not sure how important it is.

`Unable to resolve module Dimensions from /project_path/node_modules/react-native-drawer/index.js`

**Comment by rt2zz** [comment]
I think this is a react v0.6 change, will look into it tomorrow

**Comment by rt2zz** [comment]
Fixed by switching to UIManager.Dimensions in 1.2.1
