### ISSUE TITLE
How could I open the drawer using swipe upon a touchable view?

### ISSUE THREAD

**Issue by ilovelll** [root-two/react-native-drawer#205]
This is my code, alistView is a touchable listview,

```
            <View style={styles.container}>
                <Drawer ref={(ref) => this._drawer = ref} type="overlay"
                    content={exhibitor_filter}
                    tapToClose={true}

                    side="right"
                    panOpenMask={0.2}
                    openDrawerOffset={0.3} 
                    panCloseMask={0.3}
                    closedDrawerOffset={-3}
                    // styles={drawerStyles}
                    tweenHandler={(ratio) => ({
                        main: { opacity: (2 - ratio) / 2 }
                    }) } >
                    <SearchBar onSearch={(txt) => this.doTextSearch(txt) }></SearchBar>
                    {alistView}
                </Drawer>
            </View>
```

**Comment by yarilchenko** [comment]
any updates?

**Comment by jpsantos7** [comment]
+1

**Comment by yarilchenko** [comment]
@jpsantos I can provide code which works for me (little hack for this situation)

**Comment by jpsantos7** [comment]
@yarilchenko Can you please provide it? Thanks

**Comment by yarilchenko** [comment]
@jpsantos7 set `captureGestures` to `true` and `panOpenMask` to `0.01` or `0.02`
it's works for me, but need to swipe from start of screen

**Comment by yarilchenko** [comment]
@jpsantos7 slack team using same practice

**Comment by jpsantos7** [comment]
@yarilchenko  Thanks! It's not ideal because I wanted the `panCloseMask` to be larger but it will do for now

**Comment by yarilchenko** [comment]
@jpsantos7 Hello. And what the problem?) Make close mask larger, close mask didn't render while drawer is close

**Comment by jpsantos7** [comment]
@yarilchenko apparently the close mask, when open, "overlays" the drawer itself rendering the menu items unclickable. I want to make the swipeable area, when opened, as big as the screen.

**Comment by yarilchenko** [comment]
@jpsantos7 understood. If you will solve this problem - let me know please ;)

**Comment by RUIFERNANDE5** [comment]
@jpsantos7 did you resolve the overlaping issue? 
I can't press my menu burguer icon if I have 
```
captureGestures={true}
panOpenMask={0.2}
```

**Comment by jpsantos7** [comment]
@RUIFERNANDE5 Sorry, I never solved this issue.

**Comment by nguyenvanphuc2203** [comment]
any update?

**Comment by maxprihodko8** [comment]
I have tried the values:
```
captureGestures={true}
panOpenMask={0.01}
```
And have no success, it just don't work. The gesture seems not to be captured. I use the nativebase, react-router-native, here is the code: 

```
<Root>
      <Provider store={store}>
           <NativeRouter>
                <Drawer
                    type="overlay"
                    content={<MenuComponent/>}
                    tapToClose={true}
                    onClose={() => {this.props.setMenuState(false)}}
                    onOpen={() => {this.props.setMenuState(true)}}
                    open={this.props.isOpened}
                    openDrawerOffset={0.2} // 20% gap on the right side of drawer
                    panCloseMask={0.2}
                    captureGestures={true}
                    panOpenMask={0.01}
                    closedDrawerOffset={-3}
                    tweenHandler={(ratio) => ({
                        main: { opacity:(2-ratio)/2 }
                    })}
                >
                    <Switch>
                        <Route exact path="/" component={DashboardScreen} />
                        <Route exact path="/settings" component={SettingsScreen} />
                    </Switch>
                </Drawer>
            </NativeRouter>
       </Provider>
 </Root>
```

**Comment by neludac** [comment]
2 days, zero result, I'm disperate!
Swipe don't work!

**Comment by rvgroup** [comment]
try this:

```
                panOpenMask={0.2}
                negotiatePan={true}
```

**Comment by aynsdev** [comment]
this is my code and it works


`<Drawer
        type="displace"
        ref={ref => {
          this.drawer = ref
        }}
        content={
          <SideBar
            navigator={this.navigator}
            routeName={this.props.routeName}
          />
        }
        onClose={() => this.closeDrawer()}
        panOpenMask={0.2}
        negotiatePan={true}
      >
`

**Comment by josecarlosns** [comment]
I ran into this issue just now, and the `negotiatePan` option worked for me!

**Comment by rishabhshah09** [comment]
> try this:
> 
> ```
>                 panOpenMask={0.2}
>                 negotiatePan={true}
> ```

@rvgroup Thanks, Working for me
