### ISSUE TITLE
`openDrawerThreshold` does not account for `openDrawerOffset`

### ISSUE THREAD

**Issue by felixakiragreen** [root-two/react-native-drawer#21]
Ideally I would like to specify:

```
openDrawerOffset={.33}
openDrawerThreshold={.25}
```

But in this case, the threshold will apply to the opening of the drawer, but not the closing since it is already past `.25`.

Also, it would be rad to specify different thresholds for opening and closing. Maybe that is one solution for this problem, if you want to maintain threshold as a percentage of screen width.

**Comment by rt2zz** [comment]
Can you explain what is happening when you drag to close the drawer? Is it not triggering a close, even after travelling 25% of the screen?

This sounds like a bug, the intended behaivor is that it takes a 25% move from left to right to trigger opens and a 25% move from right to left to trigger closes.

**Comment by felixakiragreen** [comment]
It's trigger a close after only travelling 1% off the screen. Basically there is no buffer. I can upload a screencast if that would be helpful.

**Comment by rt2zz** [comment]
OK I think I under stand now, will take a look later

**Comment by rt2zz** [comment]
Ok should be resolved in v1.2.4

The relativeDrag prop as defaulting to false, it now defaults to true. If you do want the other behaivor you can set `relativeDrag=false`

**Comment by felixakiragreen** [comment]
Thank you very much!
