### ISSUE TITLE
Incompatible with react-relay

### ISSUE THREAD

**Issue by janaka** [root-two/react-native-drawer#216]
It would appear `react-native-drawer` is incompatible with `react-relay`. I was getting the error described here #140. TBH not sure if it's `fbemitter` or `underscore` causing the issue. Appears it's something to do with the this context or state not exising.

I've has to stop using unfortunately as I cannot figure it out.

I had it installed alongwith the following.

```
    "babel-relay-plugin": "0.9.3",
    "react": "15.3.1",
    "react-native": "0.32.0",
    "react-native-material-kit": "0.3.2",
    "react-native-vector-icons": "2.1.0",
    "react-relay": "0.9.3"
```

Windows 8 and Android.

**Comment by nikolal** [comment]
It is not about the drawer.

Did you update react or react-native recently.

There was several issues in the past with babel-relay-plugin. Babel sometimes is not binding arrow functions as expected.

You can try one of the following solutions:

1) Use babel-relay-plugin-loader

https://github.com/BerndWessels/babel-relay-plugin-loader

2) You can try using react-native-stage-0:

https://www.npmjs.com/package/babel-preset-react-native-stage-0. 

```
{
  "presets": ["react-native-stage-0"],
  "plugins": [
    "./plugins/babelRelayPlugin"
  ]
}

```

3) Before you run your app you can try:

```
watchman watch-del-all
rm -rf $TMPDIR/react-*
rm -rf node_modules
npm install
npm start --reset-cache
```

Refer to this post for more info:

http://stackoverflow.com/questions/37449580/this-is-no-longer-bound-when-using-arrow-functions-after-upgrading-to-react-nati

If you solve your issue, please post here again.

**Comment by janaka** [comment]
Since I've concluded the issue is probably specific to Windows. I believe there's a general problem with React Native on Windows dev environment. Therefore unlikely this is a react-native-drawer issue.

Worth noting that step 3 above doesn't work directly on Windows (obviously), no watchman etc.
