### ISSUE TITLE
Drawer prop side: 'right' not working

### ISSUE THREAD

**Issue by gkrinc** [root-two/react-native-drawer#219]
I have a DrawerContainer (Redux) that connects to my AppDrawer component that renders a single Drawer, but switches the content and side prop depending on which Drawer needs to be show: Burger Menu (left) and Custom Panel (right). For starters, will react-native-drawer work like this...can it be a left and right Drawer or do I need two separate Drawer components?

The left menu loads if I set the content to either the Burger Menu or Custom Panel, so the content doesn't appear to be the problem. When side is right the content isn't displayed, but looking at the inspector show this: 
![screen shot 2016-09-14 at 11 56 37 am](https://cloud.githubusercontent.com/assets/2718382/18519593/806ef76c-7a72-11e6-913d-fa6881255847.png)

Here's the return value of the render function in my AppDrawer component. Am I missing props to made side: 'right' work?:

```
return (<Drawer type={'overlay'}
                open={this.props.isNavDrawerOpen || this.props.isSecondaryDrawerOpen}
                content={drawerContent}
                side={this.props.isSecondaryDrawerOpen ? 'right' : 'left'}>
                    {React.Children.map(this.props.children, c => React.cloneElement(c, {
                        route: this.props.route
                    }))}
        </Drawer>);
```

The order in which I open the Drawers has no impact either. I can open and close left first with no issues, but the right Drawer doesn't open. If I try opening the right Drawer first it still doesn't work.

UPDATE:

I made it work by using nested Drawers:

```
return (<Drawer type={'overlay'}
                        open={this.props.isNavDrawerOpen}
                        content={<BurgerMenu onPress={this.props.toggleNavDrawer} />}
                        side={'left'}>
                            <Drawer type={'overlay'}
                                    open={this.props.isSecondaryDrawerOpen}
                                    content={<HelpDrawerContent onPress={this.props.toggleSecondaryDrawer} />}
                                    side={'right'}>
                                {React.Children.map(this.props.children, c => React.cloneElement(c, {
                                    route: this.props.route
                                }))}
                            </Drawer>
                </Drawer>);
```

**Comment by gkrinc** [comment]
Solved by using nested Drawer components

**Comment by arash-hacker** [comment]
{ 
    headerMode: 'none' , 
    `drawerPosition: 'right',`
    contentComponent: props => <Drawer {...props}
    />
}
using it also help to right side in
