### ISSUE TITLE
Drawer going too far when dragged

### ISSUE THREAD

**Issue by tnguyen42** [root-two/react-native-drawer#23]
Hi,

Has anyone found a solution in order to limit the dragging when pulling the drawing out? When I start from the left and pull it to the right, I can move the drawer to the right border. I'd like to limit this to the openDrawerOffset value.
(sorry, I wanted to make a screenshot but it doesn't seem to work on iOS Simulator)

**Comment by rt2zz** [comment]
ya, I know what you are referring to, I think this can be solved with some simple arithmetic in the pan handler, but I have not tried yet.

**Comment by rt2zz** [comment]
Ok pushed a fix for this in 1.2.6, let me know if that works for you

**Comment by tnguyen42** [comment]
Works great!
Thanks!
