### ISSUE TITLE
Issue accessing this.refs

### ISSUE THREAD

**Issue by cjmling** [root-two/react-native-drawer#24]
This is not directly related to this plugin. But I can't seems to access this.refs when I define my class like this and have a constructor like this. I can't seems to find a way or have a proper understanding how to use it in this case. Some help will be really helpful. Thanks

```
class Application extends Component {
    constructor(props) {
               super(props);
               this.state = {
                 isLoading: true,
                };
    }

    openDrawer(){
            this.refs.drawer.open()
    }
}

```

**Comment by rt2zz** [comment]
ya, there is no auto binding in es6 classes. You can bind manually

``` js
constructor(props) {
  super(props);
  this.openDrawer = this.openDrawer.bind(this)
}
```

or there are other solution as well such as es7 function binding.

**Comment by cjmling** [comment]
Yes, this works now.  A big big thanks :)

**Comment by navneetccna** [comment]
i am getting this error 

Cannot read property 'close' of undefined
handleException @ D:\nav\GSOPS\node_modules\react-native\Libraries\JavaScriptAppEngine\Initialization\ExceptionsManag…:61
handleError @ D:\nav\GSOPS\node_modules\react-native\Libraries\JavaScriptAppEngine\Initialization\InitializeJavaS…:89
reportFatalError @ D:\nav\GSOPS\node_modules\react-native\packager\react-packager\src\Resolver\polyfills\error-guard.js:30
guard @ D:\nav\GSOPS\node_modules\react-native\Libraries\Utilities\MessageQueue.js:44
callFunctionReturnFlushedQueue @ D:\nav\GSOPS\node_modules\react-native\Libraries\Utilities\MessageQueue.js:87
onmessage @ debuggerWorker.js:39

**Comment by jqn** [comment]
If having this issue please refer to this link https://facebook.github.io/react/docs/refs-and-the-dom.html
