### ISSUE TITLE
Native animated module is not available

### ISSUE THREAD

**Issue by Djakninn** [root-two/react-native-drawer#243]
### Drawer version: 2.3.0

I'm getting a `Native animated module is not available` error when I try to open the drawer. I only recently upgraded to RN 0.38, I was on 0.34 before and didn't have this problem.

**Comment by Djakninn** [comment]
Had a problem with linking RCTAnimation, not related to this module

**Comment by rgoldiez** [comment]
@Djakninn - Did you figure this out?  I had a similar issue and may be able to help you solve it, if you still have it.

**Comment by Djakninn** [comment]
Hey, thanks! Yup, I fixed it.
