### ISSUE TITLE
Close Drawer On Hardware Back Button Press

### ISSUE THREAD

**Issue by thecodecafe** [root-two/react-native-drawer#245]
Please is there some sort of way to close react router with the back button on press if open?
Below is my back button press code.

`BackAndroid.addEventListener('hardwareBackPress', () => {
		  if (self._navigator && self._navigator.getCurrentRoutes().length > 1) {
		    self._navigator.pop();
		    return true;
		  }
		  return false;
		});`
I've looked through the doc for react native drawers and can't find a way to tell if the drawer is open or closed, please how do i implement this in my code? Thanks!

**Comment by anbkit** [comment]
Hi mrbarde,
Drawer does not support method to get state, so you can use _open property of Drawer, it work ok.
```
if(drawer._open){
	drawer.close();
}
```

**Comment by sood03** [comment]
This can be achieved by adding an eventListner for back button press when the drawer is open and removing the eventListner when the drawer is closed. You may have a look a snippet below:

In Drawer component definition, set onOpen and onClose props as 
                        onOpen={this.openDrawer.bind(this)}
                        onClose={this.closeDrawer.bind(this)}

These 2 methods can be set as 

    openDrawer() {
        this.setState({
            drawerOpen: true
        });
        console.log("drawer listener added");
        BackAndroid.addEventListener('hardwareBackPress', this._handleBackPressInDrawer);
    }

    closeDrawer() {
        this.setState({
            drawerOpen: false
        });
        console.log("drawer listener removed");
        BackAndroid.removeEventListener('hardwareBackPress', this._handleBackPressInDrawer);
    }

    _handleBackPressInDrawer() {
        if (this.state.drawerOpen) {
            this.closeDrawer();
            return true;
        }
        return false;
    }

**Comment by thecodecafe** [comment]
Thanks @trongan and @sood03 both were perfect solutions to my problem, problem solved!

**Comment by sood03** [comment]
@mrbarde You may close this issue now. :)
