### ISSUE TITLE
Forcing this drawer to always display on Top ?

### ISSUE THREAD

**Issue by cjmling** [root-two/react-native-drawer#25]
I am using this plugin https://github.com/brentvatne/react-native-scrollable-tab-view . I was happy with both of the plugin only till I find that how scroll-tab work by hiding it self on the left.

So the problem happen when I open drawer I see that my hidden scrolled tab are over the drawer.

Is there any suggestion how I can force this scroll-tab to be under or force the drawer to be always on top ?

**Comment by rt2zz** [comment]
can you paste the code in question, specifically the render method that includes both the drawer and the scroll tabs?

**Comment by cjmling** [comment]
Its very much like the example 

This is the main View.
return (

```
  <View>
    <Drawer
        ref="drawer"
        type={this.state.drawerType}
        animation={this.state.animation}
        openDrawerOffset={100}
        closedDrawerOffset={this.state.closedDrawerOffset}
        panOpenMask={this.state.panOpenMask}
        panCloseMask={this.state.panCloseMask}
        relativeDrag={this.state.relativeDrag}
        panStartCompensation={this.state.panStartCompensation}
        openDrawerThreshold={this.state.openDrawerThreshold}
        content={controlPanel}
        styles={drawerStyles}
        disabled={this.state.disabled}
        tweenHandler={this.tweenHandler}
        tweenDuration={this.state.tweenDuration}
        tweenEasing={this.state.tweenEasing}
        acceptDoubleTap={this.state.acceptDoubleTap}
        acceptTap={this.state.acceptTap}
        acceptPan={this.state.acceptPan}
        changeVal={this.state.changeVal}
        side={this.state.rightSide ? 'right' : 'left'}
        onOpen={this.onOpen}
        onClose={this.onClose}>

          <View style={styles.topBar}>
              <Text style={styles.topBarMenu} onPress={this.openDrawer}>&#9776;</Text>
              <Text style={styles.topBarTitle}>{title}</Text>
              <Text style={styles.topBarRight}></Text>
          </View>

           <Portfolio /> 
      </Drawer>
  </View>
);
```

While Portfolio view is 

```
return (
      <ScrollableTabView>
        <TotalTab tabLabel="Total" portData={this.state.dataSource} />
        <ProfitTab tabLabel="Profit" portData={this.state.dataSource} />
        <LossesTab tabLabel="Losses" portData={this.state.dataSource} />
      </ScrollableTabView>
    );
```

**Comment by rt2zz** [comment]
Ok what is happening is the main view is rendered after the drawer view, hence the overlapping issue.

Its a bit of a hack, but the easiest way to fix this would be to set `type="overlay"` and then put on a custom tween handler something like:

``` js
tweenHandler={(ratio) => {
    return {
      main: { 
        left: React.NativeModules.UIManager.Dimensions.window.width*ratio
      },
    }
  }}
```

Let me know if that works. I will have to think a bit more about how this could be solved more elegantly.

**Comment by cjmling** [comment]
Thanks man it works, just a small number was required in your code to perfectly work in my case  _ratio_0.65   (I have right offset , otherwise it was pushing all content to the right off the screen).  Now not sure will it work as expected when encountering different screen size :S

![screen shot 2558-08-25 at 12 42 24 pm](https://cloud.githubusercontent.com/assets/1612187/9459557/2628ca42-4b27-11e5-8b05-73524a444ae2.png)

**Comment by cjmling** [comment]
Ok forgot that simulator have for different screen size and as expected , it does coz small issue 

Above was for iphone 4 , below is iphone 6 .

May be I should do some checking with screen size and multiply with ratio accordingly.

![screen shot 2558-08-25 at 1 08 28 pm](https://cloud.githubusercontent.com/assets/1612187/9459860/80573fbe-4b2a-11e5-8fd0-8f54c5d0de5f.png)

**Comment by rt2zz** [comment]
@cjmling is your `openDrawerOffset` an integer? Try setting the `openDrawerOffset=.35` which will treat it as a ratio. This I suspect will give you consistent behaivor across screen sizes.
