### ISSUE TITLE
Support for iPad

### ISSUE THREAD

**Issue by mrKlar** [root-two/react-native-drawer#26]
The drawer could support iPad left side menu.

**Comment by rt2zz** [comment]
you are thinking having it automatically and permanently revealed on iPad? Perhaps if the screen dimensions are past a certain threshold it can switch to "static overlay" mode.

**Comment by mrKlar** [comment]
Yes, like the actual two panel view on an ipad.  It is not an overlay however, it's the menu and the content side by side.

**Comment by rt2zz** [comment]
I like that, and it should not be too hard. Is there an ipad environment variable we can base the mode off of? I doubt I will be implementing this soon though, but I will gladly review/merge a PR

**Comment by mrKlar** [comment]
ok, if I ever get some time, I'll try to do it.

**Comment by afilp** [comment]
This is _exactly_ what I would need for an iPad application I currently develop! Do you have any plans for this?

I wonder if react-native-side-menu" supports it (I think not).

**Comment by rt2zz** [comment]
closing this in favor of https://github.com/root-two/react-native-drawer/issues/56

This may be as simple as adding a Math.min(maxValue, normalValue) at https://github.com/root-two/react-native-drawer/blob/master/index.js#L424
