### ISSUE TITLE
Clicking existing menu does not close drawer

### ISSUE THREAD

**Issue by damathryx** [root-two/react-native-drawer#260]
I have these menus:
_Home
Account
Contact Us_

**Current behavior:**

When I am currently in Home and open the drawer and click Home it does nothing since I am in the current drawer.

**Wanted behavior:** 

When I am currently in Home and open the drawer and click Home I'd like the drawer close and reset Home. 

How do I achieve this behavior?

**Comment by ollar** [comment]
Hey.
You just need to change Drawer's `open` parameter.

Like in example below:
```
<Drawer
      acceptTap
      acceptPan
      disabled={!props.drawer.get('drawerIsEnabled')}
      type="overlay"
      content={<SideMenu />}
      styles={drawerStyles}
      open={props.drawer.get('drawerIsOpen')}
      openDrawerOffset={(viewport) => {
        if (viewport.width < 400) {
          return viewport.width * 0.1;
        }
        return viewport.width - 400;
      }}
      panOpenMask={0.1}
      onOpen={() => props.dispatch(drawerOpen())}
      onClose={() => props.dispatch(drawerClose())}
      tweenHandler={ratio => ({
        mainOverlay: { opacity: (ratio - 0.2) },
      })}
    >
      {props.children}
    </Drawer>
```
I am changing it with redux.
