### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by justinmakaila** [root-two/react-native-drawer#28]
The `var deviceScreen = React.NativeModules.UIManager.Dimensions.window` module is not available in Android, and therefore needs to be updated.

Looking into what's necessary for a PR. Filing for book keeping.

**cc** @danscan

**Comment by rt2zz** [comment]
+1 I have not used react-native android yet, but I will gladly merge a PR that adds support!

As a side note I have been wanting to improve the way dimensions are handled especially as it pertains to device reorientation. Let me know what you find.

**Comment by rt2zz** [comment]
I just fixed the dimensions issue by replacing it with the new `Dimensions.get('window')` https://github.com/rt2zz/react-native-drawer/commit/da784c642cdbb7c9a992a27e27c13437a9aba17a

However in my test app the drawer seems to be buggy / extremely slow. It may be just an emulator issue. Let me know if you find out anything...

**Comment by rt2zz** [comment]
Just added support in v1.3.0, let me know how that goes

**Comment by justinmakaila** [comment]
Awesome, thanks. I'll pull it shortly.

—Justin Makaila

**Comment by justinmakaila** [comment]
I installed `1.3.0`, but I'm getting the same error I was with the old version:
![screen shot 2015-09-17 at 09 43 17](https://cloud.githubusercontent.com/assets/1638996/9934629/8ab86b6a-5d20-11e5-8c9a-a95dd514f0ba.png)

**Comment by justinmakaila** [comment]
Oops, after looking through my node_modules, I saw that there was another copy of `react-native-drawer` pointing to the wrong version.

After restarting the packager, everything seems to work.

It is a bit choppy, but the initial issue is closed. Thanks!

**Comment by rt2zz** [comment]
Ya, I see the chop too. I am hoping it is an emulator thing, but open to suggestions!

**Comment by justinmakaila** [comment]
@rt2zz Have you considered using the Animation API rather than doing that all manually?

cc @danscan

**Comment by rt2zz** [comment]
Yes, I think Animated is probably the future here, although I am not certain this will help performance much as we already use `requestAnimationFrame` + `setNativeProps`. I made another issues to track performance improvements: https://github.com/rt2zz/react-native-drawer/issues/29
