### ISSUE TITLE
Performance Enhancements

### ISSUE THREAD

**Issue by rt2zz** [root-two/react-native-drawer#29]
The existing implementation uses [tween-functions](https://www.npmjs.com/package/tween-functions) with `requestAnimationFrame` and `setNativeProps` to handle animations. This should actually be very performant, but there is potential to do more:
- [ ] Potentially some small gains to be had by switching to `Animated API`
- [ ] Implement `shouldComponentUpdate -> false` temporarily for main and drawer views during animation

**Comment by guiguan** [comment]
Hi, rt2zz

When I used your module using following configs with a long ListView, it was pretty laggy.

```
        ref="drawer"
        openDrawerThreshold={0.2}
        openDrawerOffset={0.55}
        panCloseMask={1}
        onClose={this._drawerClosed}
        onOpen={this._drawerOpened}
        styles={{
          drawer: {
            shadowColor: "#000000",
            shadowOpacity: 0.8,
            shadowRadius: 0,
          }
        }}
        tweenHandler={(ratio) => {
          return {
            drawer: { shadowRadius: Math.min(ratio*5*5, 5) },
            main: { opacity:(2-ratio)/2 },
          }
        }}
        tweenDuration={100}
```

When I removed the `tweenHandler` and changed the `type` to `overlay`, the lag seemed disappeared. It will be nice to see how Animated API performs. Apart from that, there are two options for View components: shouldRasterizeIOS and renderToHardwareTextureAndroid. My direct trial was putting them on the outmost view container of the ListView, but no performance improvement was observed.

**Comment by rt2zz** [comment]
The mechanics are basically the same without the tweenHandler set. The only difference is of course without the tween handler and with `type=overlay` the only property that is being animated is the drawer `left`.

This means the problem is likely that changing opacity on your `main` is a slow operation, which makes sense if it is a large view. I thought `shouldRasterizeIOS` would solve this, but it may not work with opacity changes.

**Comment by Mokto** [comment]
Hi @rt2zz, any update or news about this one ? :)

**Comment by rt2zz** [comment]
no news. From my experience all animations including navigator push are slow when there is a long ListView/ScrollView. I am open to suggestions for how to work around this.

**Comment by rt2zz** [comment]
performance has been improved a bit. The next big thing to consider if Animated support, but that will be a bit down the road.
