### ISSUE TITLE
Add possibility to close drawer on tap

### ISSUE THREAD

**Issue by Mokto** [root-two/react-native-drawer#30]
Hi,

I'm trying to block every event below pan mask when my drawer is open.
I also would like to close my drawer when I click on pan mask.

This is what I did with success.

``` javascript
<TouchableHighlight onPress={this.closeDrawer}
          style={{position: 'absolute',
          height: Device.height, width: DRAWER_OFFSET, top:0, left:0, opacity: this.state.isOpen?1:0}}>
            <View>
            </View>
</TouchableHighlight>
```

Would it be possible to add this as a parameter ? Or did I miss something ?

**Comment by rt2zz** [comment]
Off the top of my head, you can probbly accomplish this setting `acceptTap = true` when the drawer is open, and then setting false when it is closed. 

To do this however you would need to keep track of wether the drawer is open or not. This is possible using the onOpen/onClose props. e.g. using local component state:

``` js
  <Drawer
    onOpen={() => this.setState({drawerState: 'open'})
    onClose={() => this.setState({drawerState: 'closed'})
    acceptTap={this.state.drawerState === 'open' ? true : false}
    //...
    />
```

Using flux/redux you can do something similar but instead of setState fire an action.

Let me know if that works. Since this is a common use case (material design) I would definitely consider changing the API or adding another prop to better support this. Let me know if you have suggestions on what the props should look like.

**Comment by Mokto** [comment]
Thank for your quick answer.

Your solution is much cleaner but it doesn't prevent Touchable elements within the pan mask to be touched.

![capture d ecran 2015-09-24 a 22 41 04](https://cloud.githubusercontent.com/assets/5103928/10091798/9f583774-630d-11e5-994f-3ed87994ccbe.png)

**Comment by Mokto** [comment]
I could use your solution to prevent every Touchable to be touched too but I don't think it is very "clean"

**Comment by rt2zz** [comment]
good point, I think then `captureGestures = true` will fix that problem.

**Comment by Mokto** [comment]
Ok, thanks.

Actually, I think the behaviour is not right with captureGestures. I might be wrong ^^ but this is my workflow :
- **captureGestures={false}** : when I click on a Touchable within the pan mask, the Touchable event is called
- **captureGestures={true}** : when I click on a Touchable within the pan mask, the Touchable event is called AND the drawer is closed

**Comment by rt2zz** [comment]
ah, sounds like a bug. I am on my phone, I will have to look into it further tomorrow

**Comment by rt2zz** [comment]
I just did a test and it works for me (v1.3.0)

`captureGestures={true}` results in anything under the mask from not being touched. Can you double check your settings? 

To be clear, in the screenshot above, the left hand side is the drawer and the small section on the right is the main view correct? Also what component is managing the 'touchable' event, is it `TouchableHighlight`?

**Comment by Mokto** [comment]
To be clear, in the screenshot above, the left hand side is the drawer and the small section on the right is the main view correct? **YES**
Also what component is managing the 'touchable' event, is it TouchableHighlight? **YES**

EDIT : But you should know that I used acceptPan={false} to make the drawer open only on click.

**Comment by rt2zz** [comment]
Ah, yes accepPan was not playing well with captureGestures. I just fixed it in this commit: https://github.com/rt2zz/react-native-drawer/commit/f4caf4e21e58c4164c4d8fa436bec01583e28f9e

I have not tested it enough to feel comfortable making a new npm release, but you should be able to pull the latest from github. Let me know how it goes.

**Comment by Mokto** [comment]
Hum, in my case it's like there is an invisible pan preventing me from touching anything on the left side.

``` javascript
<Drawer ref="drawer"
              acceptPan={false}
              onOpen={() => this.setState({drawerState: 'open'})}
              onClose={() => this.setState({drawerState: 'closed'})}
              acceptTap={this.state.drawerState === 'open' ? true : false}
              captureGestures={true}
              content={<DrawerContent></DrawerContent>}
              type="static"
              openDrawerOffset={DRAWER_OFFSET}
              tweenDuration={150}>
</Drawer>
```

![capture d ecran 2015-09-25 a 15 00 10](https://cloud.githubusercontent.com/assets/5103928/10109671/5f6137d6-6396-11e5-8a9a-a84236e0d065.png)

**Comment by rt2zz** [comment]
right, this is the expected behaivor. You are probably going to want to set `panOpenMask={0}`. Alternatively (depending on your exact desired behaivor) you can set `captureGestures={this.state.drawerState === 'open' ? true : false}`

``` js
<Drawer ref="drawer"
              panOpenMask={0}
              acceptPan={false}
              onOpen={() => this.setState({drawerState: 'open'})}
              onClose={() => this.setState({drawerState: 'closed'})}
              acceptTap={this.state.drawerState === 'open' ? true : false}
              captureGestures={true}
              content={<DrawerContent></DrawerContent>}
              type="static"
              openDrawerOffset={DRAWER_OFFSET}
              tweenDuration={150}>
</Drawer>
```

**Comment by Mokto** [comment]
Works perfectly ! Thanks a lot ! :smiley:

**Comment by Mokto** [comment]
Hi,
I just updated to 1.4.2 and the bug is still present (should be fixed in commit f4caf4e)

Thanks !

**Comment by rt2zz** [comment]
Can you elaborate on what exactly is not working as expected? We discussed a few things in this thread :)

**Comment by Mokto** [comment]
Sure !

![image](https://cloud.githubusercontent.com/assets/5103928/10091798/9f583774-630d-11e5-994f-3ed87994ccbe.png)

You response was :

> Ah, yes accepPan was not playing well with captureGestures. I just fixed it in this commit: f4caf4e
> 
> I have not tested it enough to feel comfortable making a new npm release, but you should be able to pull the latest from github. Let me know how it goes.

The problem it that combining acceptPan and captureGestures, i can click on TouchableHighlight on the right side.

**Comment by rt2zz** [comment]
thank you for your awesome screenshots :+1: 

You are right, I inexplicably rolled that back in a later commit. I will fix and cut a new release shortly.

**Comment by rt2zz** [comment]
fixed https://github.com/rt2zz/react-native-drawer/commit/175249f2f1fe9e98e55b832956464fb5ab751578

**Comment by Mokto** [comment]
Perfect ! Thanks ;)
