### ISSUE TITLE
Re-Layout flicker on initial render - Android

### ISSUE THREAD

**Issue by lsfischer** [root-two/react-native-drawer#324]
Hey guys, i'm having some trouble finding this bug out 

My home screen flickers a bit (like it's resizing the screen) the first time this screen renders, but if I navigate to another screen a pop back to the home screen it works just fine.
If i remove the `<Drawer>` component the flickering goes away, so i'm assuming it comes from this component.

Does someone have any ideias as to what may cause this flickering ?

My drawer looks like this:

![image](https://user-images.githubusercontent.com/24803339/30690484-50a3d0d8-9ebc-11e7-96a7-11dc9f759b40.png)

I appreciate any advice

**Comment by lsfischer** [comment]
I found out that this flickering problem came from having `flex: 1` in my wrapped component background image, replaced it with `height: Dimensions.get('window').height` and the flickering stoped.

Closing this issue as it's resolved.

**Comment by dev4xy** [comment]
There is no other solution?

**Comment by lsfischer** [comment]
@dev4xy I haven't worked on this code for almost a year so I'm not entirely sure but I don't this flickering was due to the Drawer component, I think it was from the styles we had in our home page that got messed up somehow when we added the Drawer component (with flex: 1). Feel free to reopen this issue if this is something that's happening to you and you don't know why, hope somebody can give you a better help.

**Comment by dev4xy** [comment]
Thanks ♥
