### ISSUE TITLE
Fails on Android

### ISSUE THREAD

**Issue by kakoni** [root-two/react-native-drawer#33]
Trying this (https://gist.github.com/kakoni/83e1f2217610cc2d71ce) example on android and it fails, seeing this exception
![image](https://cloud.githubusercontent.com/assets/812150/10331686/ff80423c-6cdf-11e5-9fbd-a25a3b087d96.png)

Using react 0.13.3/native 0.11.4

**Comment by rt2zz** [comment]
hm. It was working for me on android with react-native@0.11. I will need to test this out, the error message does not look familiar.

**Comment by mchev2** [comment]
I'm getting that error on Android on react-native@0.12

**Comment by rt2zz** [comment]
Oddly this error has something to do with having a borderWidth set on the main view. I do not yet understand the the issue, but it is solved in 1.5.1 by defaulting `borderWidth: 0`

Thanks for reporting and for the gist!

**Comment by rt2zz** [comment]
Although I am getting terrible animations on android. Perhaps related to having the chrome debugger open. I think the solution to this is to migrate from `tween-functions` to `React.Animated`.

Let me know if you guys are getting animation issues as well.

**Comment by mchev2** [comment]
Error is gone in 1.5.1. I see flickering when I swipe open. Then it never opens.

**Comment by rt2zz** [comment]
@mchev2 solved 1.5.2

Apparently onLayout does not act exactly the same in android as in iOS

**Comment by mchev2** [comment]
:+1: :clap:
