### ISSUE TITLE
Incorrect Drawer Menu Width after Upgraded from 1.3.0 to 1.4.2

### ISSUE THREAD

**Issue by guiguan** [root-two/react-native-drawer#35]
Hi rt2zz,

Thanks for making such a great RN module. However, after I upgraded to your latest version from 1.3.0, my left drawer menu's width started to appear incorrectly, which spanned the whole screen instead of 45% of it (openDrawerOffset={0.45}). Nevertheless, the width of the tween transition animation was correct. I have tried to fix the problem myself by debugging your index.js, but no luck. Any clue?

Regards,
Guan

**Comment by rt2zz** [comment]
Thanks for pointing this out. In making re-orientation work I made some bad assumptions about view sizing.

I _believe_ this is fixed now in 1.4.5, although your help testing would be greatly appreciated. Let me know how it goes.

**Comment by guiguan** [comment]
Yes, I can confirm that it was fixed in 1.4.6. Cheers!
