### ISSUE TITLE
Weirdness

### ISSUE THREAD

**Issue by mschipperheyn** [root-two/react-native-drawer#36]
Getting some weirdness after updating.

General transitions now have a blue background and while I have a disabled menu, I can drag from the utmost left and drag the current page away to transition to the previous one in what looks like a kind of reverse menu operation.

**Comment by mschipperheyn** [comment]
BTW tween-function 1.0.2 installed

**Comment by rt2zz** [comment]
Can you make sure you update to the absolute latest v1.4.6. I accidentally left in a blue background during testing in an earlier version.

For the 'reverse menu operation' that sounds like the built in iOS back swipe. I believe you can disable that by setting gestures to null in your navigator: https://github.com/facebook/react-native/issues/2831 although I have not personally tried this.

**Comment by rt2zz** [comment]
scratch that, blue background is still an issue x.x

**Comment by rt2zz** [comment]
Ok should be fixed in 1.4.7
