### ISSUE TITLE
Example: RCTNetworking source files missing from project

### ISSUE THREAD

**Issue by kaydevdev** [root-two/react-native-drawer#37]
Using a fresh clone of the latest master (1.4.7), I follow instructions as described in README.md to build and run the example project in Xcode.

Xcode build fails because libRCTNetwork.a library cannot be built due to missing RCTNetworking.h and RCTNetworking.m source files.

**Comment by rt2zz** [comment]
Ok, yes it has been a while since I updated the demo, probably just needs to be linked in xcode and commited. I will take a look later, but to get it working yourself you can probably roughly follow the instructions here http://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

**Comment by josephmilla** [comment]
Nope, doesn't work :cry:

**Comment by fnoorman** [comment]
Your example is still producing error on RCTNetworking

**Comment by rt2zz** [comment]
fixed (v1.7.0). See new instructions, it now requires `npm install` from the demo directory

Let me know how that goes
