### ISSUE TITLE
[Solution] Bottom drawer

### ISSUE THREAD

**Issue by roman-rr** [root-two/react-native-drawer#384]
I don't find here bottom drawer solution, but it's called drawer. 
Also, plugin is not maintained, i propose to anybody switch to [Cupertino-Pane](https://github.com/roman-rr/cupertino-pane)

**Comment by gothraven** [comment]
@roman-rr how can [this](https://github.com/roman-rr/cupertino-pane) be a solution for a REACT NATIVE project :thinking: ? it is web only solution. you can choose the side of the drawer using the prop `side` to bottom so it can show up from the bottom !

**Comment by roman-rr** [comment]
@gothraven thanks, after research i realized that react native can't contain html components.
I will create soon some type of `core` for pane gestures, and will implement react native support from this core.
