### ISSUE TITLE
Closing drawer on disable

### ISSUE THREAD

**Issue by mschipperheyn** [root-two/react-native-drawer#39]
I have the logout button in the drawer. So, when a user logs out, I want the drawer to close and subsequently disabled.

I've tried doing it like this, both fail. The menu remains open in a disabled state. Any suggestions?

```
componentDidUpdate(prevProps){
    if(!this.props.leftMenu.enabled && prevProps.leftMenu.visible)
        this.refs.drawer.close();
}

componentWillUpdate(nextProps){
    if(!nextProps.leftMenu.enabled && this.props.leftMenu.visible)
      this.refs.drawer.close();
}
```

**Comment by mschipperheyn** [comment]
It seems that the drawer does not respond to programmatic input after it has been disabled. My take would be that it should only not respond to user input in a disabled state

**Comment by rt2zz** [comment]
I think I agree with you, and will likely change this in an upcoming release. In the meantime I recommend you use `acceptPan=false` as a substitute (this will create the behaivor you describe where programmatic effects work but pans are rejected)

**Comment by mschipperheyn** [comment]
Thanks!

**Comment by rt2zz** [comment]
You can now call drawer.open and drawer.close even when disabled (v1.6.0)
