### ISSUE TITLE
onTap should not be active in closed state

### ISSUE THREAD

**Issue by mschipperheyn** [root-two/react-native-drawer#40]
So, the problem here is that the onTap area remains active in the closed state. So that means that any time the area in say the left 50 pixels gets tapped, e.g. when activating a form element, will open the menu. 

I can't imagine any scenario where tapping the left side of the screen should open the menu. A good workaround is to have onTap={this.state.open} in stead of onTap={true} but it stills feels like a bug.

**Comment by rt2zz** [comment]
I am trying to keep the props low level and explicit. The challenge is there are so many props (by virtue of the vast number of possible desirable drawer configurations) that keeping things stable and working is a challenge. So I do not want to introduce any unneeded complexity in the form of extra if statements and ambiguous prop behaivor. 

That said I agree with your thoughts, and I think the possible solution here is to either ship pre configured drawer components like:
`<Drawer.MaterialDesign />`
or to ship pre configured drawer in a seperate module (this was actually my hope when starting this project). E.G.
`react-native-drawer-material`
`react-native-drawer-static`
`react-native-drawer-declarative`

**Comment by pppluto** [comment]
how can i click right blank to close and also retain pangesture to close?

**Comment by rt2zz** [comment]
@MrPluto not sure what you mean. tap to close and pan to close are completely independent and controlled by `acceptTap` and `acceptPan`

**Comment by pppluto** [comment]
but when two set true ,it cant work smoothly,

**Comment by rt2zz** [comment]
ah, I understand now. I am not sure, this would require a tinkering with the pan gesture handlers. It must be possible since this is roughly how scrollview works.

**Comment by rt2zz** [comment]
@mschipperheyn just released v1.8.0 which includes `tapToClose` prop, that should work as you described

**Comment by pppluto** [comment]
great ! nice work .
