### ISSUE TITLE
Question: can drawer overlay a visible Overlay

### ISSUE THREAD

**Issue by mschipperheyn** [root-two/react-native-drawer#41]
My question relates to some Overlay Toasts I use. For instance, sometimes an overlay may be active when there is no network. Right now, if I activate the drawer it will underlay that existing Overlay, which lives as a child of Drawer.

I suppose that in case of a displace configuration, I would like it to slide out of the way. In the case of an overlay configuration, I would like Drawer to overlay the Overlay/Toast. I guess, I'm looking for a z-index kind of approach.

**Comment by rt2zz** [comment]
the drawer and main are actually siblings, with which comes first depending on the `type` prop:

``` js
    return (
      <View style={this.stylesheet.container} key="drawerContainer" onLayout={this.setViewport}>
        {first}
        {second}
      </View>
    )
```

So if you have an overlay drawer (drawer is second) then anything that is a child of main should always be hidden by the drawer. It sounds to me like your toast is not a child of the main view, or if it is maybe it is using something like https://github.com/brentvatne/react-native-overlay to gain a higher than normal "z index"?

**Comment by mschipperheyn** [comment]
It is a child and I am using that exact overlay component.

**Comment by rt2zz** [comment]
I do not know how `react-native-overlay` works, but I doubt it will be compatible with what you want to achieve. Depending on your application, my recommendation would be to put your toast as the last element under your main view like follows:

``` js
<Drawer {...drawerProps}>
  <View>
    <MainAppView />
    { this.state.toast ? <Toast toast={this.state.toast /> : null }
  </View>
</Drawer>
```

`<Toast>` would then be position absolute, top: 50 or what have you.

Of course you will need to figure out how to get this.state.toast defined, possibly put on props with redux or via callback if that is your thing.

Does that work?

**Comment by rt2zz** [comment]
@mschipperheyn did you get any resolution on this? I think there is nothing we can reasonably do to support this directly within react-native-drawer, but I am pretty sure you can get it to work by messing around with your set up, and possibly making the drawer itself a overlay.
