### ISSUE TITLE
Drawer vs. Swipe-back (Android)

### ISSUE THREAD

**Issue by andreasbhansen** [root-two/react-native-drawer#42]
Hey,

So I'm using the `<Drawer />` as a navigation menu together with a `<Navigator />`. One thing I noticed is that once I've navigated and then try to open the `<Drawer />` menu again (by swiping from left to right), the `<Navigator />` will at the same time do the **swipe-back** mechanism, pushing me to the previous route. 

I've tried the `navigator.replace(route)` instead of `navigator.push(route)`, but then the transition animation no longer plays, and the view is just replaced instantly. 

Is there a way to remove the previous route (from the stack) inside the onClose event handler? Or is that bad practice? Kinda stuck here, great if someone got any ideas!

**Comment by andreasbhansen** [comment]
If I had only waited two more minutes before asking...
Disabling swipe-back: https://github.com/facebook/react-native/issues/1014#issuecomment-96272360

**Comment by rt2zz** [comment]
yes, I typically disable swipe for back
