### ISSUE TITLE
Warning with RN 0.14

### ISSUE THREAD

**Issue by Mokto** [root-two/react-native-drawer#44]
Hi man,

Got many warnings when opening or closing the drawer :

jsSchedulingOverhead (-2ms) should be positive.

Have you got any idea ?

**Comment by rt2zz** [comment]
are you debugging on device? I see this warning a lot, I do not think it is specific to the drawer: https://github.com/facebook/react-native/issues/1598

**Comment by Mokto** [comment]
Ok thank you for the explanation. Yes I was debugging on device ! ;)
