### ISSUE TITLE
acceptTap but only for closing?

### ISSUE THREAD

**Issue by pickhardt** [root-two/react-native-drawer#45]
I am using a left drawer with a right offset, and want to allow tapping on the right side to close the drawer. However, I don't want to allow tapping on the left side of the screen (when the drawer isn't open) to open the drawer. Is there a way to use acceptTap but only for closing the drawer?

On a related note, when someone taps on the right side of the screen, buttons that are partially visible can still be pressed. Is there a way to make it so tapping on the non-drawer side will just close the drawer, but won't actually use the buttons that may have been tapped?

**Comment by rt2zz** [comment]
**Tap close not open**: At present the method to achieve this is to set `onTap={this.state.open}`. 
this of course means you need to track the open state on your parent component using onOpen & onClose. I would accept a PR that adds a `tapToClose` prop which works as described.

**Gesture negotiation**: this problem is generally solved by setting `captureGesture={true}`. Let me know if that works for you.

**Comment by felixakiragreen** [comment]
I would also like to see a `tapToClose` because otherwise acceptTap={true} and dragging produces this:

I don't know if I have time to submit a PR, but I'll add it to my list.

**Comment by rt2zz** [comment]
Ah, now I understand the conflict. Just pushed a fix to master, will cut a release soon.

**Comment by rt2zz** [comment]
https://github.com/rt2zz/react-native-drawer/releases/tag/1.8.0

`tapToClose` prop
fixed tap/pan conflict

**Comment by pickhardt** [comment]
I tested it out and I think there is a bug. When I use acceptTap={true}, and the drawer is closed, my app isn't registering taps normally any longer if I tap on the left side. I am guessing there is an invisible mask that is where the offset should be, that is blocking what would otherwise work as a tap on my app's buttons.

Also, I'm using captureGestures={true}  The bug only happens when I use both captureGestures and acceptTap
