### ISSUE TITLE
Crash while running example app

### ISSUE THREAD

**Issue by ararog** [root-two/react-native-drawer#46]
I just cloned the repository locally and tried to run the example app, but I'm always getting the following message:

RNDrawerDemo[2640:380637] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'It looks like the implementationof **DEV** has changed. Update -[RCTBatchedBridge loadSource:].'

Any ideas?

**Comment by rt2zz** [comment]
did you figure out a solution?

**Comment by ararog** [comment]
Yes, my bad, I had to shutdown the server running on terminal and let it start automatically, after that the error gone, thanks for heads up!
