### ISSUE TITLE
Handler for onOpenStart / onCloseStart?

### ISSUE THREAD

**Issue by rgoldiez** [root-two/react-native-drawer#49]
Is there a handler that fires at the _start_ of an open or close?  Or a way to mimic that behavior?

**Comment by rt2zz** [comment]
There is not currently. What is your use case? 

I suspect we would actually want to expose `onPanStart` or something similar because it is more explicit and if you are triggering a open/close programatically then you already de facto have access to `onOpenStart`.

**Comment by rgoldiez** [comment]
This may sound trivial but I'm hiding the iOS status bar when the drawer is open, but when that functionality is part of the onOpen handler the status bar doesn't get hidden until the drawer has finished opening.

**Comment by rgoldiez** [comment]
In the case where I programmatically open and close the drawer (like a button press) I hide the status bar before and the open/close. But I don't see how to do that with touch events where the user simply pulls anywhere on that side of the screen.

**Comment by rt2zz** [comment]
added `onOpenStart` and `onCloseStart`, checkout v1.9.0

These are "experimental" and may be changed in the future.

Note: these props fire anytime the drawer open method is invoked, not just on pans.
