### ISSUE TITLE
provide working example for Android

### ISSUE THREAD

**Issue by venil7** [root-two/react-native-drawer#54]
currently, in `Examples` there's only project for iPhone

**Comment by rt2zz** [comment]
fwiw the project is 100% (i.e. all props) android compatible, so any iOS implementation should work out of the box in android.

**Comment by MacKentoch** [comment]
Hi, could you please provide a more _simple / basic_ example?

Current example is a full feature (that is nice but too much) so it can be tough (_more when like me you dislike ES5 way to create components and objects in general so you rewrite all_) just for a fast try.

> Current example lead to think it is complicated. Too bad... since react-native-drawer is awesome and offers so many customizations to play with.

By the way it seems like [CaptureGesture is not used](https://github.com/root-two/react-native-drawer/blob/master/examples/RNDrawerDemo/CaptureGestures.js) maybe I'm wrong?

**Comment by rt2zz** [comment]
@MacKentoch I agree a straight up realistic demo would be great. The existing example is more of a test / playground which is not so useful if you are looking for an implementation example.
