### ISSUE TITLE
this.refs is empty

### ISSUE THREAD

**Issue by venil7** [root-two/react-native-drawer#55]
I get `this.refs` as `Object {}`
and unable to `open()`/`close()` drawer

**Comment by rt2zz** [comment]
did you set `ref="drawer"` on your drawer component? 

Alternatively you can try using the drawer [via context](https://github.com/rt2zz/react-native-drawer#opening--closing-the-drawer-programmatically)

**Comment by venil7** [comment]
Updated my comment,
Yes i did,
the whole `this.refs` is undefined

**Comment by rt2zz** [comment]
sounds like you trying to access the ref before the component has finished rendering. A quick hack to test for this is to call `this.refs.drawer.open()` inside of a setTimeout. 

If this is the case you will need to refactor your code to either call drawer.open later when this.refs is defined or use the `initializeOpen` prop

**Comment by venil7** [comment]
yes, thats exactly whats happens.
suppose both `refs` and `context` initialize at the same time (at first render?),
but then I get `Drawer` instance in `refs`, but not in `context` - in context `drawer` is `undefined`

**Comment by Taakn** [comment]
Hi, I have the exact same issue. `this.refs.drawer` is empty, even if I use a timeout. I've also tried with `initializeOpen` and a state, but changing the state does not trigger render (if I hardcode `initializeOpen={true}` it displays, but changing a state variable `initializeOpen={this.state.drawerOpen}` does not work) . Any idea? I'm completely stuck. I've also tried with the context, does not work either.

**Comment by Taakn** [comment]
Okay nevermind looks like it' working. I am using a Navigator, and I had the Drawer inside the renderScene of my Navigator. I took the Drawer out and it's now wrapping around the Navigator.

**Comment by rt2zz** [comment]
@Taakn why did the Navigator interfere with the refs? Seems odd. For context, keep in mind context is only available to the children of the drawer.

**Comment by Taakn** [comment]
I don't know why the Navigator is interfering. Maybe it has something to do with this binding issue? No idea honestly http://stackoverflow.com/questions/31986126/this-refs-is-getting-undefined-in-method/31988163

**Comment by toadums** [comment]
If your drawer is in a navigator your need to access it through the navigator's refs

``` es6
const drawer = this.refs.navigator && this.refs.navigator.refs.drawer;
```

And make sure you set the ref on the Navigator as well

``` es6
render() {
  renderScene() {
    ...
    return <Drawer ref="drawer" />;
  }
  return (
    <Navigator ref="navigator" renderScene={this.renderScene} />;
  )
}
```

You could also use the call back syntax for setting refs: https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

**Comment by Taakn** [comment]
Thanks so much @toadums! I'm just starting with React Native and didn't realize refs worked that way. Everything is working smoothly right now with this excellent Drawer component! Thanks again for your help as well @rt2zz.

**Comment by rt2zz** [comment]
+1

**Comment by jqn** [comment]
If having this issue please refer to this link https://facebook.github.io/react/docs/refs-and-the-dom.html
