### ISSUE TITLE
maxOpen option

### ISSUE THREAD

**Issue by rgoldiez** [root-two/react-native-drawer#56]
Thoughts on a `maxDrawerOpen` property?  Use case is an app that is sometimes portrait, sometimes landscape.  

I use `openDrawerOffset={75}` which gives me the open drawer look I'm going for in portrait orientation.  But in landscape, the drawer opens too far.  My thought is that it'd be nice to have a max open width.  

Feedback?  Worth adding?

**Comment by rt2zz** [comment]
Try setting `openDrawerOffset={0.2}`. When the offset is a decimal it treats it as a percent instead of a nominal amount. Let me know if that satisfies your use case. If not we can discuss alternatives.

**Comment by rgoldiez** [comment]
Thanks for the feedback.  I think the method you described it better than what I was doing (w/ the fixed pixel) but it still always slide the main view over 80% of the way (revealing the drawer on most of the screen).  This is perfect (in my opinion) for a phone in portrait but less than idea for a phone in landscape (when the drawer displays a list of options or navigation routes).

**Comment by marcelglaeser** [comment]
Hey,
i have the some problem! If i change from portrait to landscape, the drawer is to large. How can i fixed?

Thanks
Marcel

**Comment by rt2zz** [comment]
Updated title. I am not sure what the best way to support this is, I am wary of adding new props. 

This can technically be achieved by checking Dimensions and passing in the according openDrawerOffset value.

**Comment by rgoldiez** [comment]
I agree... I don't think we need this.  In my specific case, I have my app set to portrait only.  But you're right, if an app supports landscape you can simply calculate the width and adjust.  I'd leave it to the user and keep this component unaware.

**Comment by rt2zz** [comment]
@rgoldiez you just gave me an idea: since the drawer already tracks layout, what if openDrawerOffset could additionally be a function:

``` js
openDrawerOffset={({width, height}) => {
  return width - 75                                   // always 75px from left
  return height < width ? 300 : 100         // larger offset in landscape
})
```

**Comment by rgoldiez** [comment]
@rt2zz - that's a very good idea.  Much better than my suggestion of having the app also call Dimension to get screen height/width.

**Comment by rt2zz** [comment]
awesome, added function support in master, will publish to npm in a few days 👍
