### ISSUE TITLE
[bug]tap cannot be recognized on iOS 9.2

### ISSUE THREAD

**Issue by viix** [root-two/react-native-drawer#58]
on 9.2 version, tap gesture cannot be recognized for gestureState.moveX is always larger than 25 in below code, unless you tap very very slightly.

``` javascript
handlePanResponderEnd (e, gestureState) {
    if (gestureState.moveX < 25 && (Date.now() - this._panStartTime < 500)) {
      this._panning = false
      this.processTapGestures()
      return
    }
```

**Comment by rt2zz** [comment]
This is a tough one, because the panStartTime is not a reliable number either. From your observation what is the typical moveX of a tap? 

Maybe we can just bump up the threshhold to 50.

**Comment by viix** [comment]
the strange thing is that in iOS 9.1 or below, it works fine, moveX is always 0 when tapping, while iOS 9.2 would be some number above 50 or something. I set threshold to 125 and works fine.

I don't know whether apple or React Native change something to gesture. maybe.

**Comment by rt2zz** [comment]
set the threshold to 100 for now in v1.10.2. This is very not idea, 100 could easily be a partial swipe. I will leave this open as a reminder to monitor (perhaps things will be smoothed out in future rn versions)
