### ISSUE TITLE
top/bottom offset

### ISSUE THREAD

**Issue by chandu0101** [root-two/react-native-drawer#59]
Hi,
    Can we have top/bottom offset so that top navbar will be functional even when drawer is opened!..

**Comment by rt2zz** [comment]
While I have not done it myself, I believe this can be achieved by setting `style={{drawer: {marginTop: 20}}}`

Let me know if that works

**Comment by chandu0101** [comment]
yeah that worked , thank you. btw why property name is `styles` ?  instead of `style`(react-native way) .

**Comment by rt2zz** [comment]
because the prop controls styles for both the drawer and main panels. Overloading style would be confusing.

**Comment by chandu0101** [comment]
makes sense , thanks for explanation :)

**Comment by chandu0101** [comment]
with this recent fix https://github.com/root-two/react-native-drawer/pull/63 , this workaround not working anymore :s

**Comment by rt2zz** [comment]
Ok, I switched from setting height to setting width. It should work as expected now.

**Comment by rt2zz** [comment]
I believe this is fully resolved with the new overlay pointerEvents behaivor. Please reopen if there is still an issue!
