### ISSUE TITLE
acceptPan prop doesn't work?

### ISSUE THREAD

**Issue by haikov** [root-two/react-native-drawer#62]
It seems like `acceptPan={false}` doesn't work. I'm trying to allow only programmatically opening with this code:

``` javascript
<Drawer
    ref="drawer"
    type="static"
    content={<Filter />}
    openDrawerOffset={0.4}
    side="right"
    tapToClose={true}
    captureGestures={true}
    acceptPan={false}
    styles={{
        drawer: {shadowColor: 'black', shadowOpacity: 0.8, shadowRadius: 3},
        main: {paddingLeft: 5}
    }}
    tweenHandler={Drawer.tweenPresets.parallax}
>
    {this.renderContent()}
</Drawer>
```

But it only disables the animation. Drawer can still be opened with swipe. Am I doing something wrong?

**Comment by rt2zz** [comment]
Good catch - this got lost during the `negotiatePans` implementation. I will readd shortly.

**Comment by milasevicius** [comment]
You can hack this with prop `panOpenMask={0.0}`

**Comment by tdugger** [comment]
Thanks @milasevicius.  I noticed this problem too.

**Comment by rt2zz** [comment]
this should be fixed in 1.16

**Comment by Taakn** [comment]
Hello, even with your latest version installed (1.16.5) I am still able to open the drawer with swipe on both iOS and Android. I am using React Native 0.19. Here is my code... Thanks!

```
<Drawer
  type="overlay"
  acceptPan={false}
  content={<View />}
  tapToClose={true}
  captureGestures={true}
  openDrawerOffset={0.2} // 20% gap on the right side of drawer
  panCloseMask={0.2}
  closedDrawerOffset={-3}
  styles={{
    drawer: {shadowColor: '#000000', shadowOpacity: 0.8, shadowRadius: 3},
    main: {paddingLeft: 3}
  }}
  tweenHandler={(ratio) => ({
    main: { opacity:(2-ratio)/2 }
   })}
/>
```

**Comment by rt2zz** [comment]
Well that is unfortunate. this time it is really fixed: https://github.com/root-two/react-native-drawer/commit/cf8426dea7764da3a5c76e078a0c444e8f719d9e

v1.16.6

**Comment by Taakn** [comment]
Thanks so much  @rt2zz it's now working on both Android and iOS
