### ISSUE TITLE
ListView Scene behind drawer is clicked by touch. I want it blocked.

### ISSUE THREAD

**Issue by changminc** [root-two/react-native-drawer#64]
I'm using the option, type="overlay". When a drawer is opened and I clicked the offset area, the scene behind drawer is clicked by touch. I want it to be blocked. 
What option dose make it possible?

Most applications close the drawer when the offset area(drawer outside) is touched. 
That's what I want. Please give me any advice.

For your reference, the scene contains <ListView /> component, and <ListView /> contains  <TouchableHighlight /> component.

**Comment by rt2zz** [comment]
short term solution: set `captureGestures=true` and make sure the panCloseMask is sufficiently large.

that said I will be cutting a release with a overlay this week that will effectively accomplish this out of the box.

**Comment by changminc** [comment]
Thank you, @rt2zz. Your temporary suggestion does work well to block clicking out of box. 
[Updated comment] But, if the `panCloseMast` value is larger than `openDrawerOffset` value, clicking something inside the box could be not available.

I appreciate for your next release in advance.

**Comment by rt2zz** [comment]
@changminc just released v1.12.0 which has an overlay that catches taps when `type='overlay'`
