### ISSUE TITLE
tapToClose not working in andorid

### ISSUE THREAD

**Issue by notlose** [root-two/react-native-drawer#65]
cannot get andorid to work on tapToClose while ios works fine

```
<Drawer 
              captureGestures={false}
              acceptPan={false}
              openDrawerThreshold={100}
              openDrawerOffset={0.2}
              tapToClose={true}
              acceptTap={true}
              ref="drawer"
              content={<ControlPanel closeDrawer={this.closeControlPanel}/>}
              closeDrawer={this.closeControlPanel}

              >
```

**Comment by rt2zz** [comment]
scratch that, fix incoming

**Comment by rt2zz** [comment]
should be fixed in 1.12.0 but your testing and confirmation would be much appreciated

**Comment by notlose** [comment]
it works now, but partial of screen tap is captured by my another component in mainview. thanks!

**Comment by rt2zz** [comment]
@notlose not sure I follow. What partial of screen is being captured? Be aware that tapToClose applies specifically to the `panCloseMask` area, so you will want to make sure panCloseMask = openDrawerOffset
