### ISSUE TITLE
disabled prop does not appear to be working

### ISSUE THREAD

**Issue by rgoldiez** [root-two/react-native-drawer#66]
I'm trying to programmatically disable the drawer (in my case, when a modal is displayed) but it does not appear to be working, even when hardcoded to 'true'.  Am I missing something or is it really broken?

**Comment by rt2zz** [comment]
It is broken. I will try to publish a new release tonight, maybe tomorrow.

**Comment by rt2zz** [comment]
just released v1.12.0 - can you verify working?

**Comment by rgoldiez** [comment]
I just pulled 1.12.0 and I don't see any improvements.  Did it make it into 1.12?  I only see commits for an overlay fix and then updating package.json to 1.12

**Comment by rt2zz** [comment]
I see, there was an outstanding bug when both negotiatePan and disabled are true. Fixed in 1.13

**Comment by rgoldiez** [comment]
Works as expected in 1.13 ... Thanks for fixing so quickly.  I really appreciate it!

**Comment by eneskaya** [comment]
Hi

I have version 1.16.7 and am trying to disable the drawer within some views.

My drawer looks like this (Drawer.ios.js):

``` javascript
      <Drawer
        ref="drawer"
        type="displace"
        tapToClose
        disabled={false}
        content={<SideMenu />}
        openDrawerOffset={0.3}
        panCloseMask={0.3}
        negotiatePan
        onOpenStart={() => this.setState({ statusBarHidden: true })}
        onCloseStart={() => this.setState({ statusBarHidden: false })}
        tweenHandler={(ratio) => ({
          main: { opacity: Math.max(1, 1 - ratio) }
        })}
      >
          <StatusBar
            hidden={this.state.statusBarHidden}
            animated
            showHideTransition="slide"
          />
          <DefaultRenderer navigationState={children[0]} />
      </Drawer>
```

I am also registering the context and am able to access it from the view, where I want to disable the drawer.

Within the render method of the view:

``` javascript
    ...
    this.context.drawer.props.disabled = true;
    ...
```

Am I missing something? I logged the `this.context.drawer` and the context is correctly given.
But the drawer is not disabled!

Thanks for an answer.

**Comment by rt2zz** [comment]
@eneskaya if you can I would recommend upgrading to 2.0 `npm i react-native-drawer@next` I will be looking to publish a RC next week, and generally i think more use cases are better supported.

**Comment by eneskaya** [comment]
@rt2zz Thanks for the quick answer. When I try to install with @next I get the output `└── react-native-drawer@2.0.0-wip1  invalid` by npm.
