### ISSUE TITLE
Two Drawers, tap to close not working

### ISSUE THREAD

**Issue by sashafklein** [root-two/react-native-drawer#70]
I'm using two drawers on different sides, in iOS. 

When I open a drawer and click on the offset area, instead of closing, it fires a press event for that area (in the main content, outside of the drawer) and doesn't fire a drawer close event. Only dragging the drawer closes it. 

My simplified code:

```
  openDrawer(side) {
    if (!this.state.openDrawer) {
      this.setState({ openDrawer: side })
      this._drawerObj(side).open()
    }
  }

  closeDrawer(side) {
    console.log('closing', side)
    if (this.state.openDrawer && this.state.openDrawer === side) {
      this._drawerObj(side).close()
      this.setState({ openDrawer: null })
    }
  }

  drawer( menuComponent, side, content ) {
    var opts = { 
      content: menuComponent, 
      ref: `drawer${side.capitalize()}`,
      openDrawerOffset: 60,
      panCloseMask: 60, // Because of this issue: https://github.com/root-two/react-native-drawer/issues/65 (Android, but figured it was transferable; no dice)
      type: 'overlay',
      side: side,
      onClose: () => this.closeDrawer(side),
      tapToClose: true,
      captureGestures: this.state.open === side // Because of this issue: https://github.com/root-two/react-native-drawer/issues/50
    }

    return <Drawer { ...opts }>
      { content }
    </Drawer>
  }


  render() {
    return this.drawer( <LeftDrawer/>, 'left', 
      this.drawer( <RightDrawer/>, 'right', 
        this.mainContent() 
      )
    )

  }
```

How do I get pressing outside of the drawer to close it, rather than fire a press event on that background content?

Thanks,

Sasha

PS -- interestingly, the `closeDrawer` function appears to be fired on page load (according to the console log). Is that potentially part of the problem?

> Could this be responsible? https://github.com/root-two/react-native-drawer/issues/58 - If so, is it fixable?

**Comment by rt2zz** [comment]
@sashafklein I am not sure what is going on. It can be a bit tedious to test these things, and to be honest not much work has gone into making sure double drawers work. If you find anything useful let me know, and I will likewise update here if I find anything.

**Comment by evanmrose** [comment]
@sashafklein I'd be interested to hear what you learned, I'm implementing a double drawer now

**Comment by sashafklein** [comment]
Hey @evanmrose - unfortunately, I tabled the project for a bit and never got to a solution that was working perfectly for me. If you end up finding one, please let me know how it works out. Am planning to tackle this against shortly, so will let you know if I figure anything out.

**Comment by rt2zz** [comment]
two drawer support has been greatly improved in v2. Let me know how that goes!
