### ISSUE TITLE
Feature Request: disable drawer programatically

### ISSUE THREAD

**Issue by fxhereng** [root-two/react-native-drawer#72]
Hi,

I would like to disable the drawer on some screens and reactivate it after in other screens, something like:

``` javascript
_drawerRef.setDisableProp(true|false)
```

I know I can do programatically close or open, but I would like to keep the close on tap gesture, and if possible the drag as well.

Thanks

Fx

**Comment by rt2zz** [comment]
@fxhereng the recommended method is to set `disabled={true}` as a prop on the drawer. Have you tried this?

**Comment by fxhereng** [comment]
Yes! But the thing is I'm using a navigator and the drawer is set on top of
it, because I want to have it overlaying the whole page. Otherwise it
doesn't overlay the navigation bar.

Each time I navigate to change page, I still have it then.

That's why I would like to enable or disable it programmatically according
the page I'm showing.

**Comment by fxhereng** [comment]
Because if I put `disable={true}` I'm loosing some features like the drag or tap to close, which is very useful.

And great work by the way.

**Comment by stephensprinkle-zz** [comment]
@fxhereng --

Came up against this scenario as well recently and there's not need for a change to react-native-drawer itself -- simply utilizing state should get things working as intended.

In my case things were similar, the drawer was the parent component of my react native router flux component.  

Handled as follows (terse, just showing the relevant bits):

```
class <classname> extends Component{
  constructor(props){
    this.state = {
      drawerDisabled: true
    }

    this.disableDrawer = this.disableDrawer.bind(this)
    this.enableDrawer = this.enableDrawer.bind(this)
  }

  disableDrawer(){
    this.setState({
      drawerDisabled: true
    })
  }

  enableDrawer(){
    this.setState({
      drawerDisabled: false
    })
  }

  render(){
    return(
      <Drawer disabled={this.state.drawerDisabled}>
       <Router>
        <Route name='something' 
          component={Something} 
          disableDrawer={this.disableDrawer} 
          enableDrawer={this.enableDrawer} />
       </Router>
      </Drawer>
    )
  }
}
```

With this in place, you can then call the disable and enable props from within the child component(s).

**Comment by rt2zz** [comment]
closing in favor of the solution (and related approaches) shown by @stephensprinkle 

ty

**Comment by fxhereng** [comment]
Thanks @stephensprinkle , I solved it using redux store props and modifying its value thanks to actions in the whole app, works great :+1:

**Comment by stephensprinkle-zz** [comment]
Even better! 👍
