### ISSUE TITLE
Opening of menu doesn't work sometimes

### ISSUE THREAD

**Issue by gorjanz** [root-two/react-native-drawer#73]
I used this component, as follows:

``` javascript
<Drawer
  ref="drawer"
  openDrawerThreshold={0}
  tapToClose={true}
  openDrawerOffset={0.2}
  content={sidemenuContent}>
  {mainWindowContent}
</Drawer>
```

and everything works ok, but very often, if I try to open the menu from the left side with a very fast and short pan, in direction to the right, the menu freezes on 10-15% width of the screen, basically where the pan ended, so it's not open, and it's not closed.
From what I've managed to discover while debugging, it seems to be the problem that the handlePanResponderEnd does not get called.

Is there something, I am missing, some prop to configure it right? Because the behavior is really not as expected and it ruins otherwise great component.

**Comment by rt2zz** [comment]
@gorjanz based on what you are saying, it may be that handlePanResponderEnd is not be a reliable method. We can consider utilizing `onPanResponderRelease` `onPanResponderTerminate`.

I will try to take a look this weekend.

**Comment by rt2zz** [comment]
@gorjanz I believe this was fixed with #76 

I will cut a new release in a few days, but feel free to install master in the meantime and test it out

**Comment by gorjanz** [comment]
I've implemented the fix locally, and I think that we will have to spend more time on this, in order to make it better, because now:
- In some cases, (I cannot get quite the hang of it, where is the limit in width) the opening does not get stuck, but it glitches by closing the menu first to the start (most left side) and then it quickly opens it to the right, and it is really not pretty
- The same thing happens when you try to open it programmatically, for example by clicking a button.

I am sorry I haven't invested more time in this, but I have been swamped this past few weeks, I will try to do a more thorough debugging session the first moment I have time.

But just to let you know, that the fix from #76 did not fix this issue, although I think that #75 describes the same situation.

**Comment by rt2zz** [comment]
ok lets keep this open then

**Comment by rt2zz** [comment]
@gorjanz if you can try out v1.15.0. There is still more work to do, but several bug fixes were landed.

**Comment by gorjanz** [comment]
I tried v1.16.7 and I think the issue is fixed. It seems as it is working as expected, and the 'getting stuck' in half-open/half-closed state is gone. Tnx for fixing it, and I am closing the issue.
