### ISSUE TITLE
How to do background overlay without opacity?

### ISSUE THREAD

**Issue by 9mm** [root-two/react-native-drawer#74]
Hey,

I'm using this lib for Android, and I know a lot of sidebar menus have a black semi-transparent overlay behind the menu but above the initial content.

I've tried doing this with the `tweenHandler` thats in the docs (via opacity), but the problem is all my position: absolute elements all switch to semi-transparent, and creates tons of discordance and confusion because every single element becomes semi see-through rather than a black semi-transparent black overlay on top.

Do you have any idea how I could solve this?

**Comment by jeffchienzabinet** [comment]
+1

**Comment by rt2zz** [comment]
This is not currently possible, but only requires a few small tweaks to make this happen. Basically we need to add some form of tween support to https://github.com/root-two/react-native-drawer/blob/master/index.js#L399

**Comment by ncnlinh** [comment]
+1

**Comment by pewh** [comment]
+1

**Comment by dgladkov** [comment]
This is possible with version 2.0.0-wip1. Example:

``` jsx
<Drawer
...
  styles={{
    mainOverlay: {
      backgroundColor: 'black',
      opacity: 0,
    },
  }}
  tweenHandler={(ratio) => ({
    mainOverlayProps: {
      opacity: ratio / 2,
    },
>
```

Example above has a black overlay that will become half transparent when drawer is fully open.

**Comment by 9mm** [comment]
:+1:

**Comment by lastant** [comment]
Should be mainOverlay instead of mainOverlayProps.
