### ISSUE TITLE
Swiping / dragging to open drawer freezes partially open when done very quickly

### ISSUE THREAD

**Issue by felixakiragreen** [root-two/react-native-drawer#75]
I was able to track it down to this part here: https://github.com/root-two/react-native-drawer/blob/master/index.js#L372-L377

I was able to fix it by adding: `if (!this._open) this.close()`

Let me know if that's the right way to fix it, if so, I can submit a PR.

**Comment by rt2zz** [comment]
Ah yes that is the right solution. PR greatly appreciated :+1:
