### ISSUE TITLE
Add blur for 'component' rendering during swipe?

### ISSUE THREAD

**Issue by aksonov** [root-two/react-native-drawer#77]
How to implement it?

**Comment by rt2zz** [comment]
as in, get the main scene to blur (similar to how in material design the main scene "fades")?

**Comment by aksonov** [comment]
Okey, looks like blur with flexible radius is not supported by React Native (and iOS) at all. But I still don't understand how to change 'main' scene during swipe. Let's say i want to make it more dark. I can't set just backgroundColor - because it contains some elements, map,etc. I can't decrease opacity, because it will make it lighter, not darker.

**Comment by rt2zz** [comment]
@aksonov yes, what people have done in the past is set your overall app background to black and then lighten the opacity (making it darker rather than lighter). You can do this by setting `styles={{main: backgroundColor: 'black'}}`

Let me know if this works for you.

**Comment by rt2zz** [comment]
@aksonov the latest release `react-native-drawer@next` now supports styles for mainOverlay which should help you achieve the desired effect. Something like:

```
tweenHandler={(ratio) => ({
  mainOverlay: {
    opacity: ratio,
    backgroundColor: 'black'
  }
})}
```

**Comment by aksonov** [comment]
@rt2zz Thanks, i will check. Sorry, missed notification about your reply 18 days ago ....

**Comment by mistryhiren94** [comment]
@aksonov thanks.
