### ISSUE TITLE
slight hang in "onClose" method

### ISSUE THREAD

**Issue by ssh-randy** [root-two/react-native-drawer#82]
So I added a navigator.push to my onClose method, so that the view would change on closing. However, just before the drawer fully closes, a small part of the drawer hangs on the UI for a split second.

my onClose looks like this:
  onClose: function(){
    if(this.state.navTo) {
      this.props.navigator.push({
        id: this.state.navTo,
        name: this.state.navTo,
      });
    }
  },

I was assuming onClose would take place after the drawer finished closing, but the animation doesn't seem to reflect that.

**Comment by rt2zz** [comment]
@cabooserwar can try upgrading to v2 and see if this is still an issue? If so some test code would help greatly! let me know

**Comment by rt2zz** [comment]
The prop is called asap. If this is still an issue please reopen

**Comment by ssh-randy** [comment]
seems to be working fine now!
