### ISSUE TITLE
Completely glitches when active call in progress

### ISSUE THREAD

**Issue by 9mm** [root-two/react-native-drawer#83]
Hey, great library!

I'm not sure if this is a problem with my app or the lib itself, but the sidebar becomes unusable if you use an app while you have a call going (and the green bar slides down).

It flickers open and fast like 30 times a second, and doesn't respond to any gestures. Can someone maybe tell me if they experience the same thing or maybe I'm doing something wrong on my end...

Thanks!

**Comment by rt2zz** [comment]
I think this is a bug. Can you clarify what you mean by "and the green bar slides down"?

I will be looking into this further shortly

**Comment by 9mm** [comment]
Sure, I mean this thing:

![image](https://cloud.githubusercontent.com/assets/1386207/12934935/1b8f8d56-cf60-11e5-9fed-5798d0dddbff.png)

**Comment by chadsmith** [comment]
I'm seeing it as well. It happens when you set StatusBarIOS to hidden.

**Comment by 9mm** [comment]
ah-ha!... interesting

**Comment by grabbou** [comment]
This is because hiding status bar hides the green bar as well which is causing `setviewport` method to be called during animation (and it force closes it).

**Comment by rt2zz** [comment]
should be fixed in 1.16.7, thanks @grabbou 

If you guys have a moment to test it would be much appreciated. There are still some edge cases with certain prop combinations that need ironing out.

**Comment by grabbou** [comment]
I am pretty sure @9mm has tested it inside out (like on regular basis I don't even check how app behaves during a call <lol>)
