### ISSUE TITLE
Error when requiring react native drawer

### ISSUE THREAD

**Issue by evanmrose** [root-two/react-native-drawer#85]
I think this may have been a goof on my part since it's so obvious but in the example, it says to use:

`Drawer = require('react-native-drawer')`

but that yields an 'expected string but got object' error. The fix was the following:

`Drawer = require('react-native-drawer').default`

Maybe the docs need an update?

**Comment by rt2zz** [comment]
Ah I forgot babel 6 recently changed the behavior, fixed in v1.16.3 :+1:

**Comment by rt2zz** [comment]
fwiw I also updated the docs to import syntax `import Drawer from 'react-native-drawer'`
