### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dyf102** [root-two/react-native-drawer#86]
react-native-cli: 0.1.10
react-native: 0.18.1

bundle: Created ReactPackager
uncaught error Error: SyntaxError: /Users/yuwei/project/swiftriders/node_modules/react-native-drawer/index.js: A semicolon is required after a class property (62:3)
  60 |     tweenHandler: React.PropTypes.func,
  61 |     type: React.PropTypes.oneOf(['overlay', 'static', 'displace']),

> 62 |   }

**Comment by rt2zz** [comment]
fixed in 1.16.3
