### ISSUE TITLE
Background Color Of Drawer

### ISSUE THREAD

**Issue by Mmarzex** [root-two/react-native-drawer#87]
Hi Is there way for the background color of the drawer to be specified so that it matches the content view. 

The two images below the one is how the content view should look and the other is how it looks when I pass it as the content prop into the drawer.
![simulator screen shot feb 14 2016 5 06 54 pm](https://cloud.githubusercontent.com/assets/41359/13036735/6fe3ea7e-d33d-11e5-9c14-561913bf3fa6.png)
![simulator screen shot feb 14 2016 5 06 50 pm](https://cloud.githubusercontent.com/assets/41359/13036736/6fe8a14a-d33d-11e5-967e-fc1a713f110f.png)

**Comment by rt2zz** [comment]
This is definitely possible, can you post your Drawer code? My guess is you need to set `backgroundColor` on your drawer container view.

**Comment by Mmarzex** [comment]
So this is for the contentView

```
const styles = StyleSheet.create({
  menu: {
    flex: 1,
    backgroundColor: 'gray',
    padding: 20,
  }
});
....
render() {
    return (

      <View style={styles.menu}>
        <View style={styles.avatarContainer}>
          <Image
            style={styles.avatar}
            source={{ uri, }}/>
          <Text style={styles.name}>Your name</Text>
        </View>
        <Text style={styles.item}>About</Text>
        <Text style={styles.item}>Contacts</Text>

      </View>
    );
  }
```

And then for the Drawer View

```
import React, {
  Component
} from 'react-native';
import Drawer from 'react-native-drawer';
import Menu from '../Menu';

class SideDrawer extends Component {
  render() {
    return(
      <Drawer
        type="static"
        content={<Menu />}
        openDrawerOffset={100}
        styles={{drawer: {backgroundColor: "gray"}}}
        tweenHandler={Drawer.tweenPresets.parallax}
        >
        {React.Children.map(this.props.children, c => React.cloneElement(c, {
        route: this.props.route
        }))}
      </Drawer>
    )
  }
}

export default SideDrawer;
```

**Comment by rt2zz** [comment]
Your code looks fine. Maybe there is something weird going on in `avatarContainer`?

I would recommend upgrading to the latest react-native and react-native-drawer and see if the issue persists

**Comment by ekryski** [comment]
I feel like you can close this @rt2zz. Setting the the `backgrounColor` in the `styles.main`, `styles.drawer` and any container or scrollview inside the drawer content or the children works perfectly.

**Comment by rt2zz** [comment]
@ekryski 👍

**Comment by keung7251** [comment]
@ekryski Is it possible to set background image in main and drawer?
