### ISSUE TITLE
Suggested way to change resize the drawer when open

### ISSUE THREAD

**Issue by agentfunk** [root-two/react-native-drawer#88]
I have a drawer opening from the left side. Within the drawer I have a set of buttons that when clicked I want to further open the drawer. Sort of like a multi step drawer. What I tried is to reset the openDrawerOffset and then call resync which does not use the animation and honestly feels wrong. Any suggestions on how to go about doing this?

**Comment by rt2zz** [comment]
This is not possible out of the box. Your approach makes sense, resync should animate so there may be a bug there.

Another option would be to expose a `animateTo` method similar to ScrollView's `scrollTo` but my concern is keeping all of the state in sync might be complex.

Let me know if you figure out something workable. I am happy to take PR's as long as they do not appreciably increase complexity.

**Comment by agentfunk** [comment]
Thanks for quick response. I'll look a little closer in a few days.

**Comment by rt2zz** [comment]
@sammerat if you are still looking for a way to make this happen let me know. resync has been reworked and greatly improved so I think the method you originally tried may work satisfactorily now.
