### ISSUE TITLE
Main view height is not updated when device-orientation changes

### ISSUE THREAD

**Issue by realjamie** [root-two/react-native-drawer#89]
In landscape mode, the children view (main view) seems to have longer height than it should be. The problem is that the height of the main view is defined in a stylesheet, and it's not updated when orientation changes (line 427-431):

```
    styles.main = Object.assign({
      position: 'absolute',
      top: 0,
      height: this.state.viewport.height, // this is not updated when orientation changes
    }, {borderWidth:0}, this.props.styles.main)
```

To solve this problem, the style of the main view (line 371) need to be `style={[this.stylesheet.main, {height: this.state.viewport.height, width: this.getMainWidth()}]}` instead of `style={[this.stylesheet.main, {width: this.getMainWidth()}]}`. Would you please test it out and verify it? Thanks.

**Comment by mboguc** [comment]
The situation is reversed when starting the application in landscape mode. After switching to portrait, main view covers only a part of the screen. The solution proposed by @realjamie works in both cases.

**Comment by realjamie** [comment]
Thanks @mboguc . I just made a pull request  https://github.com/root-two/react-native-drawer/pull/92
