### ISSUE TITLE
Better support device re-orientation

### ISSUE THREAD

**Issue by rt2zz** [root-two/react-native-drawer#9]
Perhaps via a orientation prop?

**Comment by mrKlar** [comment]
The drawer does not support device re-orientation automatically too.

**Comment by rt2zz** [comment]
do you know the idiomatic way to do this in react-native? I think possible `onLayout` prop, but I have not looked into it.

**Comment by ghost** [comment]
I have an XCode Extension that I updated that provides updated data for layout.  You could use this.  https://github.com/kkjdaniel/react-native-device-display/issues/13

**Comment by rt2zz** [comment]
just published v1.4.1, uses onLayout to support reorientation
