### ISSUE TITLE
Unable to close Drawer when starting and landscape and switching to portrait

### ISSUE THREAD

**Issue by mboguc** [root-two/react-native-drawer#90]
When starting the application in landscape mode and switching to portrait, it is impossible to close the drawer by swipe gesture. The problem lies in `testPanResponderMask`, where `deviceScreen` is being used to calculate deltas and masks. To solve this problem, it would be best to update the object by adding

```
deviceScreen = viewport
```

after setting the viewport in line 482.
Could you please verify this solution?

**Comment by rt2zz** [comment]
:+1: fixed in v2
