### ISSUE TITLE
[ES6/7 rewrite] Use fat arrow functions instead of .bind(this)

### ISSUE THREAD

**Issue by grabbou** [root-two/react-native-drawer#94]
We could potentially write:

``` js
setViewport = (viewport) => {}
```

instead of function declaration & .bind(this) in constructor, esp. since we already use class properties.

**Comment by rt2zz** [comment]
:+1: I have been working on migrating all of the methods. Help is much appreciated!

**Comment by grabbou** [comment]
I'll send the pr, thanks :)

**Comment by rt2zz** [comment]
I think I just fixed the last function. Thanks!
