### ISSUE TITLE
Best way to mimic android sidebar?

### ISSUE THREAD

**Issue by 9mm** [root-two/react-native-drawer#95]
Hey,

I'm trying to emulate the exact animation/easing/elasticity of the standard Android sidebar. A great example is the `Play Music` app. Their sidebar seems really standard and really great.

I've been struggling for quite a long time though and I just can't make it match. Do you have any ideas? I noticed when you use your finger to swipe out it 'bounces' off my thumb, as if the easing curve is not a smooth arc but more like a _/  angle.

Thanks for any possible input!

**Comment by rt2zz** [comment]
I have aspirations to implement Animated and expose more fully featured easing functions to react-native-drawer. However if your goal is specifically to achieve a native android feel, you will actually be better off going with https://github.com/iodine/react-native-drawer-layout

While lacking the customizability of this module, react-native-drawer-layout should work better for that specific use case.

**Comment by 9mm** [comment]
interesting, ok thanks!
